// src/lib/content/images.ts — Artist image resolver
// Maps artist slugs to local image paths
// Images are synced from Base44 or other sources to /public/images/artists/

const ARTIST_IMAGES: Record<string, string> = {
  // Base44 synced photos
  'calin': '/images/artists/calin.webp',
  'robin-tent': '/images/artists/robin-tent.webp',
  'majk-spirit': '/images/artists/majk-spirit.webp',
  'mejzyy': '/images/artists/mejzyy.webp',
  'redzed': '/images/artists/redzed.webp',
  'g1nter': '/images/artists/g1nter.webp',
          'dalyb': '/images/artists/dalyb.webp',
  'strapo': '/images/artists/strapo.webp',
  'nobodylisten': '/images/artists/nobodylisten.webp',
  'paulie-garand': '/images/artists/paulie-garand.webp',
  'tafrob': '/images/artists/tafrob.webp',
  'totally-nothin': '/images/artists/totally-nothin.webp',
  'separ': '/images/artists/separ.webp',
  'radikal-chef': '/images/artists/radikal-chef.webp',
  'pil-c': '/images/artists/pil-c.webp',
  'fobia-kid': '/images/artists/fobia-kid.webp',
  'forest-blunt': '/images/artists/forest-blunt.webp',
  'dame': '/images/artists/dame.webp',
  'gleb': '/images/artists/gleb.webp',
  'samey': '/images/artists/samey.webp',
  'hasan': '/images/artists/hasan.webp',
  '58g': '/images/artists/58g.webp',
      'yzomandias': '/images/artists/yzomandias.webp',
  'robin-zoot': '/images/artists/robin-zoot.webp',
  'dollar-prync': '/images/artists/dollar-prync.webp',
  'stein27': '/images/artists/stein27.webp',
  'saul': '/images/artists/saul.webp',
    'adiss': '/images/artists/adiss.webp',
  'aless': '/images/artists/aless.webp',
      'nik-tendo': '/images/artists/nik-tendo.webp',
      'rytmus': '/images/artists/rytmus.webp',
        'viktor-sheen': '/images/artists/viktor-sheen.webp',
        'hugo-toxxx': '/images/artists/hugo-toxxx.webp',
        'james-cole': '/images/artists/james-cole.webp',
        'rest': '/images/artists/rest.webp',
      'ektor': '/images/artists/ektor.webp',
    'ben-cristovao': '/images/artists/ben-cristovao.webp',
    'dj-wich': '/images/artists/dj-wich.webp',
  'dj-enemy': '/images/artists/dj-enemy.webp',
    'maniak': '/images/artists/maniak.webp',
    'michajlov': '/images/artists/michajlov.webp',
  'dj-fatte': '/images/artists/dj-fatte.webp',
  'ego': '/images/artists/ego.webp',
  'mc-gey': '/images/artists/mc-gey.webp',
  'sima': '/images/artists/sima.webp',
  'grey256': '/images/artists/grey256.webp',
  'sergei-barracuda': '/images/artists/sergei-barracuda.webp',
  'lvcas-dope': '/images/artists/lvcas-dope.webp',
  '7krat3': '/images/artists/7krat3.webp',
  'astralkid22': '/images/artists/astralkid22.webp',
  'ca-hanova-bulhar': '/images/artists/ca-hanova-bulhar.webp',
  'fosco-alma': '/images/artists/fosco-alma.webp',
  'kali': '/images/artists/kali.webp',
  'mike-trafik': '/images/artists/mike-trafik.webp',
  'psh': '/images/artists/psh.webp',
  'refew': '/images/artists/refew.webp',
  'reznik': '/images/artists/reznik.webp',
  'smack': '/images/artists/smack.webp',
  'smack-one': '/images/artists/smack-one.webp',
  'sorty': '/images/artists/sorty.webp',
  'vladimir-518': '/images/artists/vladimir-518.webp',
  'sofian-medjmedj': '/images/artists/sofian-medjmedj.webp',
  'cistychov': '/images/artists/cistychov.webp',
  'dokkeytino': '/images/artists/dokkeytino.webp',
  'protiva': '/images/artists/protiva.webp',
  'fvck-kvlt': '/images/artists/fvck-kvlt.webp',
  'lipo': '/images/artists/lipo.webp',
  'arleta': '/images/artists/arleta.webp',
  'labello': '/images/artists/labello.webp',
  'vercetti-cg': '/images/artists/vercetti-cg.webp',
  'renne-dang': '/images/artists/renne-dang.webp',
  'ptk': '/images/artists/ptk.webp',
  'bobby-blaze': '/images/artists/bobby-blaze.webp',
  'jay-diesel': '/images/artists/jay-diesel.webp',
  'sensey': '/images/artists/sensey.webp',
  'marpo': '/images/artists/marpo.webp',
  'astral': '/images/artists/astral.webp',
  'luca-brassi10x': '/images/artists/luca-brassi10x.webp',
  'boy-wonder': '/images/artists/boy-wonder.webp',
  'tenki': '/images/artists/tenki.webp',
  'palermo': '/images/artists/palermo.webp',
  'la4': '/images/artists/la4.webp',
  'dara-rolins': '/images/artists/dara-rolins.webp',
  'orion': '/images/artists/orion.webp',
  'sharlota': '/images/artists/sharlota.webp',
  'kato': '/images/artists/kato.webp',
  'karlo': '/images/artists/karlo.webp',
  'pain': '/images/artists/pain.webp',
  'koky': '/images/artists/koky.webp',
  'idea': '/images/artists/idea.webp',
  'konex': '/images/artists/konex.webp',
  'prezident-lourajder': '/images/artists/prezident-lourajder.webp',
  'shimmi': '/images/artists/shimmi.webp',
  'jickson': '/images/artists/jickson.webp',
  'kojo': '/images/artists/kojo.webp',
  'annet-x': '/images/artists/annet-x.webp',
  'hellwana': '/images/artists/hellwana.webp',
  'guapanova': '/images/artists/guapanova.webp',
  'daniel-vardan': '/images/artists/daniel-vardan.webp',
  'desade': '/images/artists/desade.webp',
  'darewin': '/images/artists/darewin.webp',
  'duan-vlk': '/images/artists/duan-vlk.webp',
  'schyzo': '/images/artists/schyzo.webp',
  'katannah': '/images/artists/katannah.webp',
  'kamil-hoffmann': '/images/artists/kamil-hoffmann.webp',
  'resetedh': '/images/artists/resetedh.webp',
  'alan-murin': '/images/artists/alan-murin.webp',
  'd-kop': '/images/artists/d-kop.webp',
  'dj-aka': '/images/artists/dj-aka.webp',
  'dorian': '/images/artists/dorian.webp',
  'hard-rico': '/images/artists/hard-rico.webp',
  'indy': '/images/artists/indy.webp',
  'marko-damian': '/images/artists/marko-damian.webp',
  'miky-mora': '/images/artists/miky-mora.webp',
  'momo': '/images/artists/momo.webp',
  'radimo': '/images/artists/radimo.webp',
  'supa': '/images/artists/supa.webp',
  'zayo': '/images/artists/zayo.webp',
};

export function getArtistImage(slug: string): string | undefined {
  return ARTIST_IMAGES[slug];
}

export function hasArtistImage(slug: string): boolean {
  return slug in ARTIST_IMAGES;
}

// Future: sync from Base44 API automatically
// export async function syncArtistImagesFromBase44() { ... }
