// ═══════════════════════════════════════════════════════════════
// AUTO-GENERATED by scripts/generate-registry.mjs
//
// NEUPRAVUJ ručně — změny se přepíší při příštím buildu.
// Přidej rapper/album/label/zanr do content/ → automaticky se zalinkuje.
//
// Vygenerováno: 2026-06-06T07:44:57.948Z
// Celkem entit: 591 (246 album, 29 label, 224 rapper, 92 zanr)
// ═══════════════════════════════════════════════════════════════

import type { InterlinkEntity } from './remark-interlinking'

export const ENTITY_REGISTRY: InterlinkEntity[] = [
  {
    "name": "[Gudlak]",
    "slug": "gudlak",
    "type": "album"
  },
  {
    "name": "1000",
    "slug": "1000",
    "type": "album"
  },
  {
    "name": "2 MOUCHY 1 RANOU",
    "slug": "2-mouchy-1-ranou",
    "type": "album"
  },
  {
    "name": "2051",
    "slug": "2051",
    "type": "album"
  },
  {
    "name": "3017",
    "slug": "3017",
    "type": "album"
  },
  {
    "name": "713",
    "slug": "713",
    "type": "album"
  },
  {
    "name": "9 Years of Moan Part 2",
    "slug": "9-years-of-moan-part-2",
    "type": "album"
  },
  {
    "name": "9EVET",
    "slug": "9evet",
    "type": "album"
  },
  {
    "name": "Ach Ano III: Ballerbyn",
    "slug": "ach-ano-iii-ballerbyn",
    "type": "album"
  },
  {
    "name": "Ach Ano Mixtape",
    "slug": "ach-ano-mixtape",
    "type": "album"
  },
  {
    "name": "Airon Meidan",
    "slug": "airon-meidan",
    "type": "album"
  },
  {
    "name": "ALIEN",
    "slug": "alien",
    "type": "album"
  },
  {
    "name": "ALIEN: Expansion Pack",
    "slug": "alien-expansion-pack",
    "type": "album"
  },
  {
    "name": "Alliwant Wax digital 001 VA",
    "slug": "alliwant-wax-digital-001-va",
    "type": "album"
  },
  {
    "name": "Alliwant Wax digital 002",
    "slug": "alliwant-wax-digital-002",
    "type": "album"
  },
  {
    "name": "Alliwant Wax digital 010",
    "slug": "alliwant-wax-digital-010",
    "type": "album"
  },
  {
    "name": "Amonit (Deluxe)",
    "slug": "amonit",
    "type": "album"
  },
  {
    "name": "Antarktida",
    "slug": "antarktida",
    "type": "album"
  },
  {
    "name": "Aura",
    "slug": "aura",
    "type": "album"
  },
  {
    "name": "Avec Moi",
    "slug": "avec-moi",
    "type": "album"
  },
  {
    "name": "Avec Moi (Kevin McKay Remix)",
    "slug": "avec-moi-kevin-mckay-remix",
    "type": "album"
  },
  {
    "name": "Babushka Traphouse",
    "slug": "babushka-traphouse",
    "type": "album"
  },
  {
    "name": "Babushka Traphouse afterparty",
    "slug": "babushka-traphouse-afterparty",
    "type": "album"
  },
  {
    "name": "Backwoods Bred",
    "slug": "backwoods-bred",
    "type": "album"
  },
  {
    "name": "Bandana",
    "slug": "bandana",
    "type": "album"
  },
  {
    "name": "Bauch Money II",
    "slug": "bauch-money-ii",
    "type": "album"
  },
  {
    "name": "BeastMode",
    "slug": "beastmode",
    "type": "album"
  },
  {
    "name": "BENİM",
    "slug": "benim",
    "type": "album"
  },
  {
    "name": "BERSERK",
    "slug": "berserk",
    "type": "album"
  },
  {
    "name": "Better Ways",
    "slug": "better-ways",
    "type": "album"
  },
  {
    "name": "Bieber Fever",
    "slug": "bieber-fever",
    "type": "album"
  },
  {
    "name": "Bieber Fever Tour Life",
    "slug": "bieber-fever-tour-life",
    "type": "album"
  },
  {
    "name": "Black Chinese II",
    "slug": "black-chinese-ii",
    "type": "album"
  },
  {
    "name": "Boomerang",
    "slug": "boomerang",
    "type": "album"
  },
  {
    "name": "Brooklyn International",
    "slug": "brooklyn-international",
    "type": "album"
  },
  {
    "name": "C.W.A",
    "slug": "c-w-a",
    "type": "album"
  },
  {
    "name": "CA$HFLOW",
    "slug": "ca-hflow",
    "type": "album"
  },
  {
    "name": "CityLights",
    "slug": "citylights",
    "type": "album"
  },
  {
    "name": "Close To Me EP",
    "slug": "close-to-me-ep",
    "type": "album"
  },
  {
    "name": "Counted Out Deluxe",
    "slug": "counted-out-deluxe",
    "type": "album"
  },
  {
    "name": "Což takhle dát si Tesař",
    "slug": "coz-takhle-dat-si-tesar",
    "type": "album"
  },
  {
    "name": "Crazy Horse",
    "slug": "crazy-horse",
    "type": "album"
  },
  {
    "name": "Crimson Stain",
    "slug": "crimson-stain",
    "type": "album"
  },
  {
    "name": "ČERNÁ VRÁNA",
    "slug": "cerna-vrana",
    "type": "album"
  },
  {
    "name": "Černej kůň",
    "slug": "cernej-kun",
    "type": "album"
  },
  {
    "name": "Černej kůň plus",
    "slug": "cernej-kun-plus",
    "type": "album"
  },
  {
    "name": "Daleko blíž",
    "slug": "daleko-bliz",
    "type": "album"
  },
  {
    "name": "Dance for You",
    "slug": "dance-for-you",
    "type": "album"
  },
  {
    "name": "DANK",
    "slug": "dank",
    "type": "album"
  },
  {
    "name": "Dead Man Walking",
    "slug": "dead-man-walking",
    "type": "album"
  },
  {
    "name": "Definice Rapu",
    "slug": "definice-rapu",
    "type": "album"
  },
  {
    "name": "Detektor",
    "slug": "detektor",
    "type": "album"
  },
  {
    "name": "Detektor II",
    "slug": "detektor-ii",
    "type": "album"
  },
  {
    "name": "Diamant",
    "slug": "diamant",
    "type": "album"
  },
  {
    "name": "Different Time",
    "slug": "different-time",
    "type": "album"
  },
  {
    "name": "Dobrá Duše, Srdce ze Zlata",
    "slug": "dobra-duse-srdce-ze-zlata",
    "type": "album"
  },
  {
    "name": "Doggin em",
    "slug": "doggin-em",
    "type": "album"
  },
  {
    "name": "Don't Stop This Feeling",
    "slug": "don-t-stop-this-feeling",
    "type": "album"
  },
  {
    "name": "Don't Tell The Truth",
    "slug": "don-t-tell-the-truth",
    "type": "album"
  },
  {
    "name": "DONE",
    "slug": "done",
    "type": "album"
  },
  {
    "name": "DOWN4LIFE",
    "slug": "down4life",
    "type": "album"
  },
  {
    "name": "Drag4Hard",
    "slug": "drag4hard",
    "type": "album"
  },
  {
    "name": "DRIPOLAR",
    "slug": "dripolar",
    "type": "album"
  },
  {
    "name": "Dropbox",
    "slug": "dropbox",
    "type": "album"
  },
  {
    "name": "EP01",
    "slug": "ep01",
    "type": "album"
  },
  {
    "name": "Every Night EP",
    "slug": "every-night-ep",
    "type": "album"
  },
  {
    "name": "F4R4on",
    "slug": "f4r4on",
    "type": "album"
  },
  {
    "name": "Fade In",
    "slug": "fade-in",
    "type": "album"
  },
  {
    "name": "Fade In (Instrumental)",
    "slug": "fade-in-instrumental",
    "type": "album"
  },
  {
    "name": "Fatte No More",
    "slug": "fatte-no-more",
    "type": "album"
  },
  {
    "name": "Feel The Groove EP",
    "slug": "feel-the-groove-ep",
    "type": "album"
  },
  {
    "name": "Feels Good",
    "slug": "feels-good",
    "type": "album"
  },
  {
    "name": "Fight",
    "slug": "fight",
    "type": "album"
  },
  {
    "name": "Finding Myself",
    "slug": "finding-myself",
    "type": "album"
  },
  {
    "name": "Finesa",
    "slug": "finesa",
    "type": "album"
  },
  {
    "name": "FLEX SYMBOL",
    "slug": "flex-symbol",
    "type": "album"
  },
  {
    "name": "French Connection / Music Is the Future",
    "slug": "french-connection-music-is-the-future",
    "type": "album"
  },
  {
    "name": "G.O.A.T.",
    "slug": "g-o-a-t",
    "type": "album"
  },
  {
    "name": "Garn Again",
    "slug": "garn-again",
    "type": "album"
  },
  {
    "name": "Get Down Ep",
    "slug": "get-down-ep",
    "type": "album"
  },
  {
    "name": "Go Get It (feat. Rasco)",
    "slug": "go-get-it-feat-rasco",
    "type": "album"
  },
  {
    "name": "GoldKid",
    "slug": "goldkid",
    "type": "album"
  },
  {
    "name": "GOLDKID: ULTIMATE SECTION",
    "slug": "goldkid-ultimate-section",
    "type": "album"
  },
  {
    "name": "GoldKiid",
    "slug": "goldkiid",
    "type": "album"
  },
  {
    "name": "Good Night",
    "slug": "good-night",
    "type": "album"
  },
  {
    "name": "Goodfellas",
    "slug": "goodfellas",
    "type": "album"
  },
  {
    "name": "Gorila vs. Architekt",
    "slug": "gorila-vs-architekt",
    "type": "album"
  },
  {
    "name": "Gril Styl",
    "slug": "gril-styl",
    "type": "album"
  },
  {
    "name": "Guestlist",
    "slug": "guestlist",
    "type": "album"
  },
  {
    "name": "Harant",
    "slug": "harant",
    "type": "album"
  },
  {
    "name": "He Is Mine",
    "slug": "he-is-mine",
    "type": "album"
  },
  {
    "name": "Heart on Fire",
    "slug": "heart-on-fire",
    "type": "album"
  },
  {
    "name": "Hello Ibiza",
    "slug": "hello-ibiza",
    "type": "album"
  },
  {
    "name": "Highs & Lows",
    "slug": "highs-lows",
    "type": "album"
  },
  {
    "name": "Hood Celebrity 2",
    "slug": "hood-celebrity-2",
    "type": "album"
  },
  {
    "name": "Hood Celebrity 3",
    "slug": "hood-celebrity-3",
    "type": "album"
  },
  {
    "name": "Horizonty",
    "slug": "horizonty",
    "type": "album"
  },
  {
    "name": "Hráč Roku Playlist",
    "slug": "hrac-roku-playlist",
    "type": "album"
  },
  {
    "name": "Chimera Pt. 3",
    "slug": "chimera-pt-3",
    "type": "album"
  },
  {
    "name": "I Can't Get You EP",
    "slug": "i-can-t-get-you-ep",
    "type": "album"
  },
  {
    "name": "I Love",
    "slug": "i-love",
    "type": "album"
  },
  {
    "name": "I'm Sorry feat. Ledniczky",
    "slug": "i-m-sorry-feat-ledniczky",
    "type": "album"
  },
  {
    "name": "Idea x Strýc Nory EP",
    "slug": "idea-x-stryc-nory-ep",
    "type": "album"
  },
  {
    "name": "Idea x TrashBoySony EP",
    "slug": "idea-x-trashboysony-ep",
    "type": "album"
  },
  {
    "name": "Idiot",
    "slug": "idiot",
    "type": "album"
  },
  {
    "name": "IF",
    "slug": "if",
    "type": "album"
  },
  {
    "name": "Imaginarium naprosto běžných podivností",
    "slug": "imaginarium-naprosto-beznych-podivnosti",
    "type": "album"
  },
  {
    "name": "It's Ak!",
    "slug": "it-s-ak",
    "type": "album"
  },
  {
    "name": "J. EDEN",
    "slug": "j-eden",
    "type": "album"
  },
  {
    "name": "J. EDEN DVA",
    "slug": "j-eden-dva",
    "type": "album"
  },
  {
    "name": "J. EDEN E-G3N (#freekarlo edition)",
    "slug": "j-eden-e-g3n",
    "type": "album"
  },
  {
    "name": "J. EDEN E-GEN (mixed by NobodyListen)",
    "slug": "j-eden-e-gen-mixed-by-nobodylisten",
    "type": "album"
  },
  {
    "name": "Jeden",
    "slug": "jeden",
    "type": "album"
  },
  {
    "name": "JUSTiCE44 (Ledová Cesta)",
    "slug": "justice44-ledova-cesta",
    "type": "album"
  },
  {
    "name": "JUSTiCE44 (Mixtape1)",
    "slug": "justice44-mixtape1",
    "type": "album"
  },
  {
    "name": "Kapitán Láska (Deluxe Edition)",
    "slug": "kapitan-laska",
    "type": "album"
  },
  {
    "name": "Keep on Lovin' Me",
    "slug": "keep-on-lovin-me",
    "type": "album"
  },
  {
    "name": "Khumba",
    "slug": "khumba",
    "type": "album"
  },
  {
    "name": "Kila Zdarma (Mixtape)",
    "slug": "kila-zdarma-mixtape",
    "type": "album"
  },
  {
    "name": "KINGPIN",
    "slug": "kingpin",
    "type": "album"
  },
  {
    "name": "Koupili jsme Boha, aby za nás makal",
    "slug": "koupili-jsme-boha-aby-za-nas-makal",
    "type": "album"
  },
  {
    "name": "Krtek Forever",
    "slug": "krtek-forever",
    "type": "album"
  },
  {
    "name": "KRTEK MONEY LIFE",
    "slug": "krtek-money-life",
    "type": "album"
  },
  {
    "name": "Kruhy & Vlny",
    "slug": "kruhy-a-vlny",
    "type": "album"
  },
  {
    "name": "Kruhy & Vlny (217 Twins Edition)",
    "slug": "kruhy-vlny",
    "type": "album"
  },
  {
    "name": "Let Me Tell You",
    "slug": "let-me-tell-you",
    "type": "album"
  },
  {
    "name": "Live @ O2 arena Praha",
    "slug": "live-o2-arena-praha",
    "type": "album"
  },
  {
    "name": "Maison Maniak",
    "slug": "maison-maniak",
    "type": "album"
  },
  {
    "name": "Make It Hot",
    "slug": "make-it-hot",
    "type": "album"
  },
  {
    "name": "Malý Pepek Mixtape Vol. 1",
    "slug": "maly-pepek-mixtape-vol-1",
    "type": "album"
  },
  {
    "name": "MAMUTI L.P.",
    "slug": "mamuti-l-p",
    "type": "album"
  },
  {
    "name": "Man of the Century",
    "slug": "man-of-the-century",
    "type": "album"
  },
  {
    "name": "Maniak Muzik",
    "slug": "maniak-muzik",
    "type": "album"
  },
  {
    "name": "ManTime",
    "slug": "mantime",
    "type": "album"
  },
  {
    "name": "Marko",
    "slug": "marko",
    "type": "album"
  },
  {
    "name": "Medusa",
    "slug": "medusa",
    "type": "album"
  },
  {
    "name": "Medusa II",
    "slug": "medusa-ii",
    "type": "album"
  },
  {
    "name": "Melanž",
    "slug": "melanz",
    "type": "album"
  },
  {
    "name": "Menaces & Opportunités",
    "slug": "menaces-opportunites",
    "type": "album"
  },
  {
    "name": "Mezi prsty",
    "slug": "mezi-prsty",
    "type": "album"
  },
  {
    "name": "Mezitím",
    "slug": "mezitim",
    "type": "album"
  },
  {
    "name": "Miss You",
    "slug": "miss-you",
    "type": "album"
  },
  {
    "name": "Moby Dick",
    "slug": "moby-dick",
    "type": "album"
  },
  {
    "name": "Molo",
    "slug": "molo",
    "type": "album"
  },
  {
    "name": "Molo II (Deluxe)",
    "slug": "molo-ii",
    "type": "album"
  },
  {
    "name": "Monology",
    "slug": "monology",
    "type": "album"
  },
  {
    "name": "Mozoly",
    "slug": "mozoly",
    "type": "album"
  },
  {
    "name": "Mr. Sergei B",
    "slug": "mr-sergei-b",
    "type": "album"
  },
  {
    "name": "Mumie (Deluxe)",
    "slug": "mumie",
    "type": "album"
  },
  {
    "name": "Nadzemí",
    "slug": "nadzemi",
    "type": "album"
  },
  {
    "name": "NAHORU NA DNO",
    "slug": "nahoru-na-dno",
    "type": "album"
  },
  {
    "name": "Nech Rusa flexit EP",
    "slug": "nech-rusa-flexit-ep",
    "type": "album"
  },
  {
    "name": "Never Ever Ep",
    "slug": "never-ever-ep",
    "type": "album"
  },
  {
    "name": "NIBIRU",
    "slug": "nibiru",
    "type": "album"
  },
  {
    "name": "Nirvana",
    "slug": "nirvana",
    "type": "album"
  },
  {
    "name": "No Album",
    "slug": "no-album",
    "type": "album"
  },
  {
    "name": "No Title",
    "slug": "no-title",
    "type": "album"
  },
  {
    "name": "No Words Needed",
    "slug": "no-words-needed",
    "type": "album"
  },
  {
    "name": "Noční vidění",
    "slug": "nocni-videni",
    "type": "album"
  },
  {
    "name": "O beatech a lidech",
    "slug": "o-beatech-a-lidech",
    "type": "album"
  },
  {
    "name": "O beatech a remixech",
    "slug": "o-beatech-a-remixech",
    "type": "album"
  },
  {
    "name": "O Rakvích A Lidech",
    "slug": "o-rakvich-a-lidech",
    "type": "album"
  },
  {
    "name": "Off Season",
    "slug": "off-season",
    "type": "album"
  },
  {
    "name": "OneWay",
    "slug": "oneway",
    "type": "album"
  },
  {
    "name": "Opičí král vrací úder",
    "slug": "opici-kral-vraci-uder",
    "type": "album"
  },
  {
    "name": "Original",
    "slug": "original",
    "type": "album"
  },
  {
    "name": "Orikoule",
    "slug": "orikoule",
    "type": "album"
  },
  {
    "name": "P's A Love",
    "slug": "ps-a-love",
    "type": "album"
  },
  {
    "name": "Pár listov z roku 2009",
    "slug": "par-listov-z-roku-2009",
    "type": "album"
  },
  {
    "name": "Paranoia",
    "slug": "paranoia",
    "type": "album"
  },
  {
    "name": "Piedestal EP",
    "slug": "piedestal-ep",
    "type": "album"
  },
  {
    "name": "Pod Vlivem",
    "slug": "pod-vlivem",
    "type": "album"
  },
  {
    "name": "PONYA",
    "slug": "ponya",
    "type": "album"
  },
  {
    "name": "POPSTAR",
    "slug": "popstar",
    "type": "album"
  },
  {
    "name": "Pouliční Ekonomická 3: Láska & Loyalita",
    "slug": "poulicni-ekonomicka-3-laska-loyalita",
    "type": "album"
  },
  {
    "name": "Premiéra",
    "slug": "premiera",
    "type": "album"
  },
  {
    "name": "Produkt",
    "slug": "produkt",
    "type": "album"
  },
  {
    "name": "Prozyum",
    "slug": "prozyum",
    "type": "album"
  },
  {
    "name": "Puls",
    "slug": "puls",
    "type": "album"
  },
  {
    "name": "Rap",
    "slug": "rap",
    "type": "album"
  },
  {
    "name": "rap disco revoluce",
    "slug": "rap-disco-revoluce",
    "type": "album"
  },
  {
    "name": "Reflex",
    "slug": "reflex",
    "type": "album"
  },
  {
    "name": "Rep",
    "slug": "rep",
    "type": "album"
  },
  {
    "name": "RIOT",
    "slug": "riot",
    "type": "album"
  },
  {
    "name": "Road 2 Redemption",
    "slug": "road-2-redemption",
    "type": "album"
  },
  {
    "name": "ROADTRIP",
    "slug": "roadtrip",
    "type": "album"
  },
  {
    "name": "Rodinnej Typ",
    "slug": "rodinnej-typ",
    "type": "album"
  },
  {
    "name": "ROMEO",
    "slug": "romeo",
    "type": "album"
  },
  {
    "name": "Řev",
    "slug": "rev",
    "type": "album"
  },
  {
    "name": "Sbohem Roxano",
    "slug": "sbohem-roxano",
    "type": "album"
  },
  {
    "name": "Short Stories",
    "slug": "short-stories",
    "type": "album"
  },
  {
    "name": "Short Stories 2",
    "slug": "short-stories-2",
    "type": "album"
  },
  {
    "name": "Showtime",
    "slug": "showtime",
    "type": "album"
  },
  {
    "name": "skibidi alpha wolf type shi ep",
    "slug": "skibidi-alpha-wolf-type-shi-ep",
    "type": "album"
  },
  {
    "name": "Slova",
    "slug": "slova",
    "type": "album"
  },
  {
    "name": "Somebody That I Used To Know",
    "slug": "somebody-that-i-used-to-know",
    "type": "album"
  },
  {
    "name": "Soundtrack",
    "slug": "soundtrack",
    "type": "album"
  },
  {
    "name": "Soundtrack (Instrumentals)",
    "slug": "soundtrack-instrumentals",
    "type": "album"
  },
  {
    "name": "Space Lopata",
    "slug": "space-lopata",
    "type": "album"
  },
  {
    "name": "SRÁT NA TO KDO JE KRÁL",
    "slug": "srat-na-to-kdo-je-kral",
    "type": "album"
  },
  {
    "name": "Starship: Oblivion",
    "slug": "starship-oblivion",
    "type": "album"
  },
  {
    "name": "Stop Play",
    "slug": "stop-play",
    "type": "album"
  },
  {
    "name": "StreamTape",
    "slug": "streamtape",
    "type": "album"
  },
  {
    "name": "StreamTape: Vítěznej oblouk",
    "slug": "streamtape-viteznej-oblouk",
    "type": "album"
  },
  {
    "name": "Street Sermons, Vol. 1",
    "slug": "street-sermons-vol-1",
    "type": "album"
  },
  {
    "name": "Střepy",
    "slug": "strepy",
    "type": "album"
  },
  {
    "name": "Svědomí",
    "slug": "svedomi",
    "type": "album"
  },
  {
    "name": "Svetelný meč",
    "slug": "svetelny-mec",
    "type": "album"
  },
  {
    "name": "SWAG",
    "slug": "swag",
    "type": "album"
  },
  {
    "name": "SWAG SIDE STORY",
    "slug": "swag-side-story",
    "type": "album"
  },
  {
    "name": "Talkshow",
    "slug": "talkshow",
    "type": "album"
  },
  {
    "name": "Tango & Kouř",
    "slug": "tango-kour",
    "type": "album"
  },
  {
    "name": "Tempo",
    "slug": "tempo",
    "type": "album"
  },
  {
    "name": "Tempo (Instrumental)",
    "slug": "tempo-instrumental",
    "type": "album"
  },
  {
    "name": "Teritorium I",
    "slug": "teritorium-i",
    "type": "album"
  },
  {
    "name": "Teritorium II",
    "slug": "teritorium-ii",
    "type": "album"
  },
  {
    "name": "Teritorium III.",
    "slug": "teritorium-iii",
    "type": "album"
  },
  {
    "name": "Teritorium Remixy",
    "slug": "teritorium-remixy",
    "type": "album"
  },
  {
    "name": "Tetris",
    "slug": "tetris",
    "type": "album"
  },
  {
    "name": "The Prodigal Son",
    "slug": "the-prodigal-son",
    "type": "album"
  },
  {
    "name": "The Text",
    "slug": "the-text",
    "type": "album"
  },
  {
    "name": "Through These Eyes",
    "slug": "through-these-eyes",
    "type": "album"
  },
  {
    "name": "THUG LOVE SOFIA",
    "slug": "thug-love-sofia",
    "type": "album"
  },
  {
    "name": "TIMBERLAKETRAPPED",
    "slug": "timberlaketrapped",
    "type": "album"
  },
  {
    "name": "TIMBERLAKETRAPPED 2",
    "slug": "timberlaketrapped-2",
    "type": "album"
  },
  {
    "name": "To je vražda, napsal",
    "slug": "to-je-vrazda-napsal",
    "type": "album"
  },
  {
    "name": "Top Threat",
    "slug": "top-threat",
    "type": "album"
  },
  {
    "name": "TopProdukt",
    "slug": "topprodukt",
    "type": "album"
  },
  {
    "name": "Topství",
    "slug": "topstvi",
    "type": "album"
  },
  {
    "name": "Ultra! Ultra!",
    "slug": "ultra-ultra",
    "type": "album"
  },
  {
    "name": "Utržený sluchátko / Puma",
    "slug": "utrzeny-sluchatko-puma",
    "type": "album"
  },
  {
    "name": "V hlavní roli",
    "slug": "v-hlavni-roli",
    "type": "album"
  },
  {
    "name": "Vítej mezi náma (NobodyListen Remix)",
    "slug": "vitej-mezi-nama-nobodylisten-remix",
    "type": "album"
  },
  {
    "name": "WAGWAN",
    "slug": "wagwan",
    "type": "album"
  },
  {
    "name": "Walking On EP",
    "slug": "walking-on-ep",
    "type": "album"
  },
  {
    "name": "Weekend EP",
    "slug": "weekend-ep",
    "type": "album"
  },
  {
    "name": "WELL DONE",
    "slug": "well-done",
    "type": "album"
  },
  {
    "name": "White Boy",
    "slug": "white-boy",
    "type": "album"
  },
  {
    "name": "Wygrałem EP",
    "slug": "wygra-em-ep",
    "type": "album"
  },
  {
    "name": "Young Guns 01.",
    "slug": "young-guns-01",
    "type": "album"
  },
  {
    "name": "Young Guns 03.",
    "slug": "young-guns-03",
    "type": "album"
  },
  {
    "name": "Yzomandias (Remaster)",
    "slug": "yzomandias",
    "type": "album"
  },
  {
    "name": "Yzotape",
    "slug": "yzotape",
    "type": "album"
  },
  {
    "name": "Ze Dna",
    "slug": "ze-dna",
    "type": "album"
  },
  {
    "name": "Zhora Vypadá Všechno Líp",
    "slug": "zhora-vypada-vsechno-lip",
    "type": "album"
  },
  {
    "name": "ZPÁTKY NA SVOJÍ PLANETU",
    "slug": "zpatky-na-svoji-planetu",
    "type": "album"
  },
  {
    "name": "100K",
    "slug": "100k",
    "type": "label"
  },
  {
    "name": "1312 Records",
    "slug": "1312-records",
    "type": "label"
  },
  {
    "name": "415 02 Records",
    "slug": "415-02-records",
    "type": "label"
  },
  {
    "name": "44 Enterprise",
    "slug": "44-enterprise",
    "type": "label"
  },
  {
    "name": "Archetyp 51",
    "slug": "archetyp-51",
    "type": "label"
  },
  {
    "name": "Azurit Kingdom",
    "slug": "azurit-kingdom",
    "type": "label"
  },
  {
    "name": "BiggBoss",
    "slug": "biggboss",
    "type": "label"
  },
  {
    "name": "BipolarSnowBlood",
    "slug": "bipolarsnowblood",
    "type": "label"
  },
  {
    "name": "Black Sheep Cartel",
    "slug": "black-sheep-cartel",
    "type": "label"
  },
  {
    "name": "Blakkwood Records",
    "slug": "blakkwood-records",
    "type": "label"
  },
  {
    "name": "Central Gang",
    "slug": "central-gang",
    "type": "label"
  },
  {
    "name": "Comebackgang",
    "slug": "comebackgang",
    "type": "label"
  },
  {
    "name": "Detektor Records",
    "slug": "detektor-records",
    "type": "label"
  },
  {
    "name": "Dvojlitrboyzz",
    "slug": "dvojlitrboyzz",
    "type": "label"
  },
  {
    "name": "Everydays",
    "slug": "everydays",
    "type": "label"
  },
  {
    "name": "F*CK THEM",
    "slug": "fuck-them",
    "type": "label"
  },
  {
    "name": "Fuerza Arma",
    "slug": "fuerza-arma",
    "type": "label"
  },
  {
    "name": "Golden Touch",
    "slug": "golden-touch",
    "type": "label"
  },
  {
    "name": "Hypno808",
    "slug": "hypno-808",
    "type": "label"
  },
  {
    "name": "Churaq Clique",
    "slug": "churaq-clique",
    "type": "label"
  },
  {
    "name": "Mike Roft Records",
    "slug": "mike-roft",
    "type": "label"
  },
  {
    "name": "Milion+",
    "slug": "milion-plus",
    "type": "label"
  },
  {
    "name": "Pozor Records",
    "slug": "pozor-records",
    "type": "label"
  },
  {
    "name": "PVP Label",
    "slug": "pvp-label",
    "type": "label"
  },
  {
    "name": "Rychlí Kluci",
    "slug": "rychli-kluci",
    "type": "label"
  },
  {
    "name": "Skerocuda",
    "slug": "skerocuda",
    "type": "label"
  },
  {
    "name": "TroubleGang",
    "slug": "troublegang",
    "type": "label"
  },
  {
    "name": "Ty Nikdy",
    "slug": "ty-nikdy",
    "type": "label"
  },
  {
    "name": "ZNK (Zevlounská Neporažená Komise)",
    "slug": "znk",
    "type": "label"
  },
  {
    "name": "58G",
    "slug": "58g",
    "type": "rapper",
    "aliases": [
      "Karel Kučera",
      "TK27"
    ]
  },
  {
    "name": "Aless",
    "slug": "aless",
    "type": "rapper",
    "aliases": [
      "Alessia Capparelli"
    ]
  },
  {
    "name": "Alla Xul Elu",
    "slug": "alla-xul-elu",
    "type": "rapper",
    "aliases": [
      "Vampire",
      "Mr. Hyde",
      "Geno Cultshit"
    ]
  },
  {
    "name": "Annet X",
    "slug": "annet-x",
    "type": "rapper",
    "aliases": [
      "Aneta Charitonova"
    ]
  },
  {
    "name": "Ariez Baby",
    "slug": "ariez-baby",
    "type": "rapper",
    "aliases": [
      "Tengku Ariez Hazaril",
      "Baby Goth"
    ]
  },
  {
    "name": "Arleta",
    "slug": "arleta",
    "type": "rapper",
    "aliases": [
      "Arleta Berndorff"
    ]
  },
  {
    "name": "Astral One",
    "slug": "astral-one",
    "type": "rapper",
    "aliases": [
      "A1",
      "Astral"
    ]
  },
  {
    "name": "AstralKid22",
    "slug": "astralkid22",
    "type": "rapper",
    "aliases": [
      "Neveřejné (údajně něco s ‚K‘)",
      "AK22",
      "Kid"
    ]
  },
  {
    "name": "BADBOY BERLIN",
    "slug": "badboy-berlin",
    "type": "rapper",
    "aliases": [
      "Neznámý (údajně německo-český původ)",
      "BBB",
      "BadBoy"
    ]
  },
  {
    "name": "Ben Cristovao",
    "slug": "ben-cristovao",
    "type": "rapper",
    "aliases": [
      "Ben da Silva Cristóvão"
    ]
  },
  {
    "name": "Big Boy Kea",
    "slug": "big-boy-kea",
    "type": "rapper",
    "aliases": [
      "Neznámý (údajně Keanu Johnson)",
      "Kea",
      "Big Kea"
    ]
  },
  {
    "name": "Big Narstie",
    "slug": "big-narstie",
    "type": "rapper",
    "aliases": [
      "Tyrone Mark Lindo",
      "Narstie",
      "Tyrone"
    ]
  },
  {
    "name": "Blako",
    "slug": "blako",
    "type": "rapper",
    "aliases": [
      "Neznámý (údajně spojený s projektem *Rise of the Warrior Cop*)",
      "Blak-O",
      "B-Lako"
    ]
  },
  {
    "name": "Bobby Blaze",
    "slug": "bobby-blaze",
    "type": "rapper",
    "aliases": [
      "Blaze"
    ]
  },
  {
    "name": "Boy Wonder",
    "slug": "boy-wonder",
    "type": "rapper",
    "aliases": [
      "Lukáš Jedlička"
    ]
  },
  {
    "name": "C-Gun",
    "slug": "c-gun",
    "type": "rapper"
  },
  {
    "name": "CA$HANOVA BULHAR",
    "slug": "ca-hanova-bulhar",
    "type": "rapper",
    "aliases": [
      "Matěj Kratejl",
      "Cashanova Bulhar"
    ]
  },
  {
    "name": "Calin",
    "slug": "calin",
    "type": "rapper",
    "aliases": [
      "Călin Panfili"
    ]
  },
  {
    "name": "Cavalier",
    "slug": "cavalier",
    "type": "rapper",
    "aliases": [
      "Jakub Sokolowski"
    ]
  },
  {
    "name": "CJBIGSMOKE",
    "slug": "cjbigsmoke",
    "type": "rapper"
  },
  {
    "name": "Clemens",
    "slug": "clemens",
    "type": "rapper"
  },
  {
    "name": "Clemens & Jon",
    "slug": "clemens-jon",
    "type": "rapper"
  },
  {
    "name": "Crudd2Active",
    "slug": "crudd2active",
    "type": "rapper"
  },
  {
    "name": "CRYSTAL KIDZ",
    "slug": "crystal-kidz",
    "type": "rapper"
  },
  {
    "name": "Čistychov",
    "slug": "cistychov",
    "type": "rapper",
    "aliases": [
      "Daniel Chládek"
    ]
  },
  {
    "name": "D Ritch",
    "slug": "d-ritch",
    "type": "rapper",
    "aliases": [
      "Fred Ritchin / Ritch C. Savin-Williams (pravděpodobně pseudonymní spojení)"
    ]
  },
  {
    "name": "D.Kop",
    "slug": "d-kop",
    "type": "rapper",
    "aliases": [
      "Neznámý (údajně spojen s projektem JMPZ)",
      "D.K.P.",
      "Dívčí Kop"
    ]
  },
  {
    "name": "Dalyb",
    "slug": "dalyb",
    "type": "rapper",
    "aliases": [
      "Dalibor Štofan"
    ]
  },
  {
    "name": "Daniel Vardan",
    "slug": "daniel-vardan",
    "type": "rapper",
    "aliases": [
      "Daniel Pavliš"
    ]
  },
  {
    "name": "Dano Kapitán",
    "slug": "dano-kapitan",
    "type": "rapper",
    "aliases": [
      "Daniel Kapitán",
      "Kapitán Korkorán",
      "Dano K.",
      "Korky"
    ]
  },
  {
    "name": "David Beng Rostaš",
    "slug": "david-beng-rostas",
    "type": "rapper",
    "aliases": [
      "David Rostaš",
      "Beng",
      "Bengoro"
    ]
  },
  {
    "name": "Decky",
    "slug": "decky",
    "type": "rapper",
    "aliases": [
      "Neznámé (možná Děcký, Decky Ortega)",
      "Děcký",
      "Decky Ortega"
    ]
  },
  {
    "name": "DEJV",
    "slug": "dejv",
    "type": "rapper",
    "aliases": [
      "David Smetana",
      "Dejv Smetana"
    ]
  },
  {
    "name": "DeSade",
    "slug": "desade",
    "type": "rapper",
    "aliases": [
      "Michal Schmutzer"
    ]
  },
  {
    "name": "DJ AKA",
    "slug": "dj-aka",
    "type": "rapper",
    "aliases": [
      "David Jekyll",
      "Aka Manah",
      "DAvID"
    ]
  },
  {
    "name": "DJ Fatte",
    "slug": "dj-fatte",
    "type": "rapper",
    "aliases": [
      "Martin Fatka",
      "Fatte",
      "DJ Fatty"
    ]
  },
  {
    "name": "DJ Kadr",
    "slug": "dj-kadr",
    "type": "rapper",
    "aliases": [
      "Neznámé (neveřejné)",
      "Kadr",
      "DJ Kadr x Totally Nothin"
    ]
  },
  {
    "name": "Dj Opia",
    "slug": "dj-opia",
    "type": "rapper",
    "aliases": [
      "Roman Ševčík",
      "Opia",
      "DJ Opia"
    ]
  },
  {
    "name": "DJ Wich",
    "slug": "dj-wich",
    "type": "rapper",
    "aliases": [
      "Tomáš Pechlák",
      "Wich"
    ]
  },
  {
    "name": "DMS",
    "slug": "dms",
    "type": "rapper"
  },
  {
    "name": "Dokkeytino",
    "slug": "dokkeytino",
    "type": "rapper",
    "aliases": [
      "Ivan Oravec"
    ]
  },
  {
    "name": "Dollar Prync",
    "slug": "dollar-prync",
    "type": "rapper"
  },
  {
    "name": "Dominik Grey",
    "slug": "dominik-grey",
    "type": "rapper",
    "aliases": [
      "Dominik Šrom"
    ]
  },
  {
    "name": "Dorian",
    "slug": "dorian",
    "type": "rapper",
    "aliases": [
      "David Albrecht"
    ]
  },
  {
    "name": "DPLMT",
    "slug": "dplmt",
    "type": "rapper"
  },
  {
    "name": "DUPPY",
    "slug": "duppy",
    "type": "rapper"
  },
  {
    "name": "Dusan Vlk",
    "slug": "dusan-vlk",
    "type": "rapper"
  },
  {
    "name": "Ego",
    "slug": "ego",
    "type": "rapper",
    "aliases": [
      "Michal Straka"
    ]
  },
  {
    "name": "Eight O",
    "slug": "eight-o",
    "type": "rapper"
  },
  {
    "name": "Ektor",
    "slug": "ektor",
    "type": "rapper",
    "aliases": [
      "Marko Elefteriadis"
    ]
  },
  {
    "name": "El Nino",
    "slug": "el-nino",
    "type": "rapper",
    "aliases": [
      "Jan Mančík"
    ]
  },
  {
    "name": "Elektrickmann",
    "slug": "elektrickmann",
    "type": "rapper"
  },
  {
    "name": "Eliozie",
    "slug": "eliozie",
    "type": "rapper"
  },
  {
    "name": "Fleixxer P",
    "slug": "fleixxer-p",
    "type": "rapper"
  },
  {
    "name": "Fobia Kid",
    "slug": "fobia-kid",
    "type": "rapper",
    "aliases": [
      "Mateus Mampouya"
    ]
  },
  {
    "name": "Forest Blunt",
    "slug": "forest-blunt",
    "type": "rapper"
  },
  {
    "name": "Frank Flames",
    "slug": "frank-flames",
    "type": "rapper"
  },
  {
    "name": "Fuckstroy",
    "slug": "fuckstroy",
    "type": "rapper"
  },
  {
    "name": "Fvck_Kvlt",
    "slug": "fvck-kvlt",
    "type": "rapper",
    "aliases": [
      "Denis Bango"
    ]
  },
  {
    "name": "G1nter",
    "slug": "g1nter",
    "type": "rapper",
    "aliases": [
      "Michal Günter"
    ]
  },
  {
    "name": "Gizmo",
    "slug": "gizmo",
    "type": "rapper"
  },
  {
    "name": "Gleb",
    "slug": "gleb",
    "type": "rapper",
    "aliases": [
      "Gleb Veselov"
    ]
  },
  {
    "name": "guapanova",
    "slug": "guapanova",
    "type": "rapper"
  },
  {
    "name": "Haades",
    "slug": "haades",
    "type": "rapper"
  },
  {
    "name": "Hard Rico",
    "slug": "hard-rico",
    "type": "rapper",
    "aliases": [
      "Enrico Pešta"
    ]
  },
  {
    "name": "Harvey HF",
    "slug": "harvey-hf",
    "type": "rapper"
  },
  {
    "name": "Hasan",
    "slug": "hasan",
    "type": "rapper",
    "aliases": [
      "Josef Andreas"
    ]
  },
  {
    "name": "Hattori",
    "slug": "hattori",
    "type": "rapper"
  },
  {
    "name": "Hellwana",
    "slug": "hellwana",
    "type": "rapper"
  },
  {
    "name": "Hex Rated",
    "slug": "hex-rated",
    "type": "rapper"
  },
  {
    "name": "Hirmix",
    "slug": "hirmix",
    "type": "rapper"
  },
  {
    "name": "Horror Avantgarda",
    "slug": "horror-avantgarda",
    "type": "rapper"
  },
  {
    "name": "Hugo Toxxx",
    "slug": "hugo-toxxx",
    "type": "rapper",
    "aliases": [
      "Jan Daněk"
    ]
  },
  {
    "name": "Hyny the Kid",
    "slug": "hyny-the-kid",
    "type": "rapper",
    "aliases": [
      "Hynek-Martin Krčma"
    ]
  },
  {
    "name": "Chacharski",
    "slug": "chacharski",
    "type": "rapper",
    "aliases": [
      "Josef Stolař"
    ]
  },
  {
    "name": "Chachi",
    "slug": "chachi",
    "type": "rapper"
  },
  {
    "name": "Chawo",
    "slug": "chawo",
    "type": "rapper"
  },
  {
    "name": "Chetta",
    "slug": "chetta",
    "type": "rapper"
  },
  {
    "name": "Chubeats",
    "slug": "chubeats",
    "type": "rapper"
  },
  {
    "name": "Idea",
    "slug": "idea",
    "type": "rapper",
    "aliases": [
      "Josef Změlík"
    ]
  },
  {
    "name": "Igor",
    "slug": "igor",
    "type": "rapper"
  },
  {
    "name": "Indy",
    "slug": "indy",
    "type": "rapper",
    "aliases": [
      "Andreas Christodoulou"
    ]
  },
  {
    "name": "Infernal",
    "slug": "infernal",
    "type": "rapper"
  },
  {
    "name": "James Cole",
    "slug": "james-cole",
    "type": "rapper",
    "aliases": [
      "Daniel Ďurech"
    ]
  },
  {
    "name": "Jana Kirschner",
    "slug": "jana-kirschner",
    "type": "rapper"
  },
  {
    "name": "Jay Amo",
    "slug": "jay-amo",
    "type": "rapper"
  },
  {
    "name": "Jay Diesel",
    "slug": "jay-diesel",
    "type": "rapper",
    "aliases": [
      "Jiří Rejfíř"
    ]
  },
  {
    "name": "Jeremy Carr",
    "slug": "jeremy-carr",
    "type": "rapper"
  },
  {
    "name": "Jickson",
    "slug": "jickson",
    "type": "rapper",
    "aliases": [
      "Mathivendhan",
      "JCK",
      "Jackson"
    ]
  },
  {
    "name": "Johnson",
    "slug": "johnson",
    "type": "rapper"
  },
  {
    "name": "Johny Machette",
    "slug": "johny-machette",
    "type": "rapper",
    "aliases": [
      "Jonáš Čumrik"
    ]
  },
  {
    "name": "Jon",
    "slug": "jon",
    "type": "rapper"
  },
  {
    "name": "Joshua",
    "slug": "joshua",
    "type": "rapper"
  },
  {
    "name": "Kamil Hoffmann",
    "slug": "kamil-hoffmann",
    "type": "rapper",
    "aliases": [
      "Kamil",
      "KH",
      "Hoffmann"
    ]
  },
  {
    "name": "Karlo",
    "slug": "karlo",
    "type": "rapper",
    "aliases": [
      "Karlo Island",
      "Karlo-Ferdinand"
    ]
  },
  {
    "name": "Katannah",
    "slug": "katannah",
    "type": "rapper",
    "aliases": [
      "Timothy Vanke"
    ]
  },
  {
    "name": "Kato",
    "slug": "kato",
    "type": "rapper",
    "aliases": [
      "Adam Svatoš"
    ]
  },
  {
    "name": "Kenny Rough",
    "slug": "kenny-rough",
    "type": "rapper"
  },
  {
    "name": "Klára Jánská",
    "slug": "klara-janska",
    "type": "rapper"
  },
  {
    "name": "Kojo",
    "slug": "kojo",
    "type": "rapper",
    "aliases": [
      "William Mendonça Sachambula"
    ]
  },
  {
    "name": "Koky",
    "slug": "koky",
    "type": "rapper"
  },
  {
    "name": "Koukr",
    "slug": "koukr",
    "type": "rapper",
    "aliases": [
      "Richard Klement"
    ]
  },
  {
    "name": "Kvítek",
    "slug": "kvitek",
    "type": "rapper",
    "aliases": [
      "Libor Kvítek",
      "Kvítek z horroru"
    ]
  },
  {
    "name": "LA4",
    "slug": "la4",
    "type": "rapper",
    "aliases": [
      "Martin Somr"
    ]
  },
  {
    "name": "Labello – pražský rapper s břitvou v ruce a rtěnkou na rtech",
    "slug": "labello",
    "type": "rapper",
    "aliases": [
      "Lukáš Labík",
      "Laba"
    ]
  },
  {
    "name": "Laris Diam",
    "slug": "laris-diam",
    "type": "rapper"
  },
  {
    "name": "Lil Quill",
    "slug": "lil-quill",
    "type": "rapper"
  },
  {
    "name": "Lipo",
    "slug": "lipo",
    "type": "rapper",
    "aliases": [
      "Jonáš Červinka"
    ]
  },
  {
    "name": "Loko Loko",
    "slug": "loko-loko",
    "type": "rapper"
  },
  {
    "name": "Lord Goat",
    "slug": "lord-goat",
    "type": "rapper"
  },
  {
    "name": "Loudz1",
    "slug": "loudz1",
    "type": "rapper",
    "aliases": [
      "Lukáš Loudil",
      "Loud",
      "Loud One"
    ]
  },
  {
    "name": "LU2 Vinyl Flexer",
    "slug": "lu2-vinyl-flexer",
    "type": "rapper"
  },
  {
    "name": "Luca Brassi10x",
    "slug": "luca-brassi10x",
    "type": "rapper",
    "aliases": [
      "Luka Mašulovič"
    ]
  },
  {
    "name": "Luisa",
    "slug": "luisa",
    "type": "rapper"
  },
  {
    "name": "Lvcas Dope",
    "slug": "lvcas-dope",
    "type": "rapper",
    "aliases": [
      "Lukas Çakmak (původně Lukáš Navrátil)"
    ]
  },
  {
    "name": "Magenta",
    "slug": "magenta",
    "type": "rapper"
  },
  {
    "name": "Majk Spirit",
    "slug": "majk-spirit",
    "type": "rapper",
    "aliases": [
      "Michal Dušička"
    ]
  },
  {
    "name": "MAKIN HOLLOV",
    "slug": "makin-hollov",
    "type": "rapper"
  },
  {
    "name": "Maniak",
    "slug": "maniak",
    "type": "rapper",
    "aliases": [
      "Jiří Veselý"
    ]
  },
  {
    "name": "Marcus Revolta",
    "slug": "marcus-revolta",
    "type": "rapper",
    "aliases": [
      "Marek Kaleta"
    ]
  },
  {
    "name": "Marger",
    "slug": "marger",
    "type": "rapper"
  },
  {
    "name": "Marpo",
    "slug": "marpo",
    "type": "rapper",
    "aliases": [
      "Otakar Petřina"
    ]
  },
  {
    "name": "Martina Pártlová",
    "slug": "martina-partlova",
    "type": "rapper"
  },
  {
    "name": "Maxo",
    "slug": "maxo",
    "type": "rapper"
  },
  {
    "name": "Mc Cumblood",
    "slug": "mc-cumblood",
    "type": "rapper"
  },
  {
    "name": "MC Gey",
    "slug": "mc-gey",
    "type": "rapper",
    "aliases": [
      "Jakub Rafael"
    ]
  },
  {
    "name": "MDMX",
    "slug": "mdmx",
    "type": "rapper"
  },
  {
    "name": "Mega M",
    "slug": "mega-m",
    "type": "rapper"
  },
  {
    "name": "Meiton",
    "slug": "meiton",
    "type": "rapper"
  },
  {
    "name": "Meizyy",
    "slug": "meizyy",
    "type": "rapper",
    "aliases": [
      "Matěj Dejdar"
    ]
  },
  {
    "name": "Michajlov",
    "slug": "michajlov",
    "type": "rapper",
    "aliases": [
      "Michal Michajlov"
    ]
  },
  {
    "name": "Mike Trafik",
    "slug": "mike-trafik",
    "type": "rapper"
  },
  {
    "name": "Milion Plus",
    "slug": "milion-plus",
    "type": "rapper"
  },
  {
    "name": "Milli Major",
    "slug": "milli-major",
    "type": "rapper"
  },
  {
    "name": "Morpheus",
    "slug": "morpheus",
    "type": "rapper"
  },
  {
    "name": "Mr Be",
    "slug": "mr-be",
    "type": "rapper"
  },
  {
    "name": "Negash Ali",
    "slug": "negash-ali",
    "type": "rapper"
  },
  {
    "name": "Nia",
    "slug": "nia",
    "type": "rapper"
  },
  {
    "name": "Nik Tendo",
    "slug": "nik-tendo",
    "type": "rapper",
    "aliases": [
      "Dominik Citta"
    ]
  },
  {
    "name": "Nobodylisten",
    "slug": "nobodylisten",
    "type": "rapper"
  },
  {
    "name": "nolackinswayy",
    "slug": "nolackinswayy",
    "type": "rapper"
  },
  {
    "name": "O.D.",
    "slug": "o-d",
    "type": "rapper"
  },
  {
    "name": "OFF CULTURE",
    "slug": "off-culture",
    "type": "rapper"
  },
  {
    "name": "Orion",
    "slug": "orion",
    "type": "rapper",
    "aliases": [
      "Michal Opletal"
    ]
  },
  {
    "name": "P T K",
    "slug": "ptk",
    "type": "rapper",
    "aliases": [
      "Patrik Aišman"
    ]
  },
  {
    "name": "P.A.T.",
    "slug": "p-a-t",
    "type": "rapper"
  },
  {
    "name": "Pain",
    "slug": "pain",
    "type": "rapper",
    "aliases": [
      "Vojtěch Krbec"
    ]
  },
  {
    "name": "Palermo",
    "slug": "palermo",
    "type": "rapper"
  },
  {
    "name": "Patrik Love ICY L",
    "slug": "patrik-love-icy-l",
    "type": "rapper"
  },
  {
    "name": "Paulie Garand",
    "slug": "paulie-garand",
    "type": "rapper",
    "aliases": [
      "Pavel Harant"
    ]
  },
  {
    "name": "Pil C",
    "slug": "pil-c",
    "type": "rapper",
    "aliases": [
      "Lukáš Kajanovič"
    ]
  },
  {
    "name": "Pissed Chriss",
    "slug": "pissed-chriss",
    "type": "rapper"
  },
  {
    "name": "Plio",
    "slug": "plio",
    "type": "rapper"
  },
  {
    "name": "Porsche Boy",
    "slug": "porsche-boy",
    "type": "rapper",
    "aliases": [
      "Michal Hlivák"
    ]
  },
  {
    "name": "Poyeeblo CG",
    "slug": "poyeeblo-cg",
    "type": "rapper"
  },
  {
    "name": "Press Premium",
    "slug": "press-premium",
    "type": "rapper",
    "aliases": [
      "Kevin Kahl, Sanchez22, CJBIGSMOKE, Voyag"
    ]
  },
  {
    "name": "Pretorian",
    "slug": "pretorian",
    "type": "rapper",
    "aliases": [
      "Jakub Gazdík"
    ]
  },
  {
    "name": "Prezident Lourajder",
    "slug": "prezident-lourajder",
    "type": "rapper",
    "aliases": [
      "Michal Ormandík"
    ]
  },
  {
    "name": "Protiva",
    "slug": "protiva",
    "type": "rapper",
    "aliases": [
      "Pavel Protiva"
    ]
  },
  {
    "name": "Radek Škarohlíd",
    "slug": "radek-skarohlid",
    "type": "rapper"
  },
  {
    "name": "Redzed",
    "slug": "redzed",
    "type": "rapper",
    "aliases": [
      "Zdeněk Veselý"
    ]
  },
  {
    "name": "Refew",
    "slug": "refew",
    "type": "rapper",
    "aliases": [
      "Erik Gábor"
    ]
  },
  {
    "name": "Renne Dang",
    "slug": "renne-dang",
    "type": "rapper",
    "aliases": [
      "René Dang"
    ]
  },
  {
    "name": "Resetedh",
    "slug": "resetedh",
    "type": "rapper",
    "aliases": [
      "Adam Houšť"
    ]
  },
  {
    "name": "Rest",
    "slug": "rest",
    "type": "rapper",
    "aliases": [
      "Adam Chlpík"
    ]
  },
  {
    "name": "Ricky Sixx",
    "slug": "ricky-sixx",
    "type": "rapper"
  },
  {
    "name": "Robin Tent",
    "slug": "robin-tent",
    "type": "rapper",
    "aliases": [
      "Robin Stanka"
    ]
  },
  {
    "name": "Robin Zoot",
    "slug": "robin-zoot",
    "type": "rapper",
    "aliases": [
      "Robert Pouzar"
    ]
  },
  {
    "name": "Robis Hood",
    "slug": "robis-hood",
    "type": "rapper"
  },
  {
    "name": "Rollsout",
    "slug": "rollsout",
    "type": "rapper"
  },
  {
    "name": "Rudolphh",
    "slug": "rudolphh",
    "type": "rapper"
  },
  {
    "name": "Rytmus",
    "slug": "rytmus",
    "type": "rapper",
    "aliases": [
      "Patrik Vrbovský"
    ]
  },
  {
    "name": "Řezník",
    "slug": "reznik",
    "type": "rapper",
    "aliases": [
      "Martin Pohl"
    ]
  },
  {
    "name": "Sakito",
    "slug": "sakito",
    "type": "rapper"
  },
  {
    "name": "Samey",
    "slug": "samey",
    "type": "rapper",
    "aliases": [
      "Samuel Chalupka",
      "Sameyko"
    ]
  },
  {
    "name": "Sara Rikas",
    "slug": "sara-rikas",
    "type": "rapper",
    "aliases": [
      "Sára Štoselová"
    ]
  },
  {
    "name": "Saul",
    "slug": "saul",
    "type": "rapper"
  },
  {
    "name": "Scum",
    "slug": "scum",
    "type": "rapper"
  },
  {
    "name": "Sebastian",
    "slug": "sebastian",
    "type": "rapper"
  },
  {
    "name": "Sensey",
    "slug": "sensey",
    "type": "rapper"
  },
  {
    "name": "Separ",
    "slug": "separ",
    "type": "rapper",
    "aliases": [
      "Michael Kmeť"
    ]
  },
  {
    "name": "Serega",
    "slug": "serega",
    "type": "rapper",
    "aliases": [
      "Marcel"
    ]
  },
  {
    "name": "Sergei Barracuda",
    "slug": "sergei-barracuda",
    "type": "rapper",
    "aliases": [
      "Erik Peter"
    ]
  },
  {
    "name": "Shadow D",
    "slug": "shadow-d",
    "type": "rapper",
    "aliases": [
      "Radek Freimann"
    ]
  },
  {
    "name": "Shaka CG",
    "slug": "shaka-cg",
    "type": "rapper"
  },
  {
    "name": "SharkaSs",
    "slug": "sharkass",
    "type": "rapper",
    "aliases": [
      "Shárka Geroldová"
    ]
  },
  {
    "name": "Sharlota",
    "slug": "sharlota",
    "type": "rapper",
    "aliases": [
      "Šarlota Eva Tabita Frantinová"
    ]
  },
  {
    "name": "SHIMMI",
    "slug": "shimmi",
    "type": "rapper"
  },
  {
    "name": "Sima",
    "slug": "sima",
    "type": "rapper",
    "aliases": [
      "Simona Hégerová"
    ]
  },
  {
    "name": "SIMILIVINLIFE",
    "slug": "similivinlife",
    "type": "rapper"
  },
  {
    "name": "Slimeshotz",
    "slug": "slimeshotz",
    "type": "rapper"
  },
  {
    "name": "Smack One",
    "slug": "smack",
    "type": "rapper",
    "aliases": [
      "Jakub Janeček"
    ]
  },
  {
    "name": "Sofian Medjmedj",
    "slug": "sofian-medjmedj",
    "type": "rapper",
    "aliases": [
      "Sofian"
    ]
  },
  {
    "name": "Stein27",
    "slug": "stein27",
    "type": "rapper",
    "aliases": [
      "Petr Adámek"
    ]
  },
  {
    "name": "Strapo",
    "slug": "strapo",
    "type": "rapper"
  },
  {
    "name": "Supa",
    "slug": "supa",
    "type": "rapper"
  },
  {
    "name": "Sxmpra",
    "slug": "sxmpra",
    "type": "rapper"
  },
  {
    "name": "Tafrob",
    "slug": "tafrob",
    "type": "rapper",
    "aliases": [
      "Pavel Sup"
    ]
  },
  {
    "name": "Tenki",
    "slug": "tenki",
    "type": "rapper",
    "aliases": [
      "Petr Götz"
    ]
  },
  {
    "name": "Terri B!",
    "slug": "terri-b",
    "type": "rapper"
  },
  {
    "name": "The Mag",
    "slug": "the-mag",
    "type": "rapper"
  },
  {
    "name": "Tchagun",
    "slug": "tchagun",
    "type": "rapper"
  },
  {
    "name": "TK27",
    "slug": "tk27",
    "type": "rapper",
    "aliases": [
      "Kučera (křestní jméno nezveřejněno)"
    ]
  },
  {
    "name": "Tom Necrocock",
    "slug": "tom-necrocock",
    "type": "rapper"
  },
  {
    "name": "Tomás Hájícek",
    "slug": "tomas-hajicek",
    "type": "rapper"
  },
  {
    "name": "Tomáš Botló",
    "slug": "tomas-botlo",
    "type": "rapper"
  },
  {
    "name": "Totally Nothin",
    "slug": "totally-nothin",
    "type": "rapper"
  },
  {
    "name": "Tyler Durden",
    "slug": "tyler-durden",
    "type": "rapper",
    "aliases": [
      "David Štilip"
    ]
  },
  {
    "name": "U$O",
    "slug": "u-o",
    "type": "rapper"
  },
  {
    "name": "Vaclav Noid Barta",
    "slug": "vaclav-noid-barta",
    "type": "rapper"
  },
  {
    "name": "Vaclav Roucek",
    "slug": "vaclav-roucek",
    "type": "rapper"
  },
  {
    "name": "Vercetti CG",
    "slug": "vercetti-cg",
    "type": "rapper",
    "aliases": [
      "Dominik Vyšata"
    ]
  },
  {
    "name": "Viktor Sheen",
    "slug": "viktor-sheen",
    "type": "rapper",
    "aliases": [
      "Viktor Dundič"
    ]
  },
  {
    "name": "Vladimir 518",
    "slug": "vladimir-518",
    "type": "rapper",
    "aliases": [
      "Vladimír Brož"
    ]
  },
  {
    "name": "Vlaďkysyn",
    "slug": "vladkysyn",
    "type": "rapper"
  },
  {
    "name": "Vypsaná Fixa",
    "slug": "vypsana-fixa",
    "type": "rapper"
  },
  {
    "name": "weeklyn",
    "slug": "weeklyn",
    "type": "rapper"
  },
  {
    "name": "Yambro",
    "slug": "yambro",
    "type": "rapper",
    "aliases": [
      "Vanesa Jambrozyová"
    ]
  },
  {
    "name": "Young Leosia",
    "slug": "young-leosia",
    "type": "rapper",
    "aliases": [
      "Sara Leokadia Sudoł"
    ]
  },
  {
    "name": "Young Rip",
    "slug": "young-rip",
    "type": "rapper"
  },
  {
    "name": "Yzomandias",
    "slug": "yzomandias",
    "type": "rapper",
    "aliases": [
      "Jakub Vlček"
    ]
  },
  {
    "name": "Zabson",
    "slug": "zabson",
    "type": "rapper"
  },
  {
    "name": "Zef",
    "slug": "zef",
    "type": "rapper"
  },
  {
    "name": "Zkrat Kratochvíl",
    "slug": "zkrat-kratochvil",
    "type": "rapper"
  },
  {
    "name": "Abstract Hip Hop",
    "slug": "abstract-hip-hop",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Academic Rap",
    "slug": "academic-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Afro Rap",
    "slug": "afro-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Afrobeats",
    "slug": "afrobeats",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Alternative Hip Hop",
    "slug": "alternative-hip-hop",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Alternative Rap",
    "slug": "alternative-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Ambient Rap",
    "slug": "ambient-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Art Rap",
    "slug": "art-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Bassline",
    "slug": "bassline",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Boom Bap",
    "slug": "boom-bap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Britský hip hop",
    "slug": "britsky-hip-hop",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Cloud Rap",
    "slug": "cloud-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Comedy Rap",
    "slug": "comedy-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Comic Book Rap",
    "slug": "comic-book-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Conceptual Rap",
    "slug": "conceptual-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Conscious Rap",
    "slug": "conscious-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Country Rap",
    "slug": "country-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Czech Pop",
    "slug": "czech-pop",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Czech Rap",
    "slug": "czech-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Dance Rap",
    "slug": "dance-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Dancehall",
    "slug": "dancehall",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Dark Rap",
    "slug": "dark-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Dark Trap",
    "slug": "dark-trap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Drill",
    "slug": "drill",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Drum and Bass",
    "slug": "drum-and-bass",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Drum and Bass (MC kultura)",
    "slug": "drum-and-bass-mc",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "East Coast Rap",
    "slug": "east-coast-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Electronic Rap",
    "slug": "electronic-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Emo rap",
    "slug": "emo-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Experimental Hip Hop",
    "slug": "experimental-hip-hop",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Experimental Rap",
    "slug": "experimental-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Experimental Trap",
    "slug": "experimental-trap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Freestyle Rap",
    "slug": "freestyle-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Gangsta Rap",
    "slug": "gangsta-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Garage Punk",
    "slug": "garage-punk",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Glitch Hop",
    "slug": "glitch-hop",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Gothic Rap",
    "slug": "gothic-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Grime",
    "slug": "grime",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Hardcore Punk",
    "slug": "hardcore-punk",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Hardcore Rap",
    "slug": "hardcore-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Hip-hop",
    "slug": "hip-hop",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Horrorcore",
    "slug": "horrorcore",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "House Rap",
    "slug": "house-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Jazz Rap",
    "slug": "jazz-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Jungle (MC kultura)",
    "slug": "jungle-mc",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Lo-Fi Rap",
    "slug": "lo-fi-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Lyrical Rap",
    "slug": "lyrical-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Mafioso Rap",
    "slug": "mafioso-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Mainstream Rap",
    "slug": "mainstream-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Melodic Rap",
    "slug": "melodic-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Melodic Trap",
    "slug": "melodic-trap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Modern Rap",
    "slug": "modern-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Mumble Rap",
    "slug": "mumble-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Mystical Rap",
    "slug": "mystical-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Mythological Rap",
    "slug": "mythological-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Nu Metal",
    "slug": "nu-metal",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Oriental Rap",
    "slug": "oriental-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Party Rap",
    "slug": "party-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Political Punk",
    "slug": "political-punk",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Political Rap",
    "slug": "political-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Pop",
    "slug": "pop",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Pop-rap",
    "slug": "pop-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Pop-rock",
    "slug": "pop-rock",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Pornorap",
    "slug": "pornorap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Power Metal",
    "slug": "power-metal",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Psychedelic Rap",
    "slug": "psychedelic-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Punk",
    "slug": "punk",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Punk Rap",
    "slug": "punk-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "R&B (Contemporary R&B)",
    "slug": "rnb",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Rage",
    "slug": "rage",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Rap",
    "slug": "rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Rap Metal",
    "slug": "rap-metal",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Reggaeton",
    "slug": "reggaeton",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Road Rap",
    "slug": "road-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Rock-Rap",
    "slug": "rock-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Sad Rap",
    "slug": "sad-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Shock Rap",
    "slug": "shock-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Slovak Rap",
    "slug": "slovak-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Soul",
    "slug": "soul",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Southern Rap",
    "slug": "southern-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Spoken Word",
    "slug": "spoken-word",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Street Rap",
    "slug": "street-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Theater Rap",
    "slug": "theater-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Traditional Metal",
    "slug": "traditional-metal",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Trap",
    "slug": "trap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Trap Metal",
    "slug": "trap-metal",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Turntablism",
    "slug": "turntablism",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "UK Garage",
    "slug": "uk-garage",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "UK Rap",
    "slug": "uk-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Underground Hip Hop",
    "slug": "underground-hip-hop",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Underground Rap",
    "slug": "underground-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Underground Rock",
    "slug": "underground-rock",
    "type": "zanr",
    "caseSensitive": false
  }
]

export function getRegistryStats() {
  const byType = ENTITY_REGISTRY.reduce<Record<string, number>>((acc, e) => {
    acc[e.type] = (acc[e.type] || 0) + 1
    return acc
  }, {})
  return {
    total: ENTITY_REGISTRY.length,
    byType,
    totalAliases: ENTITY_REGISTRY.reduce((sum, e) => sum + (e.aliases?.length || 0), 0),
  }
}
