// ═══════════════════════════════════════════════════════════════
// AUTO-GENERATED by scripts/generate-registry.mjs
//
// NEUPRAVUJ ručně — změny se přepíší při příštím buildu.
// Přidej rapper/album/label/zanr do content/ → automaticky se zalinkuje.
//
// Vygenerováno: 2026-06-08T15:32:58.784Z
// Celkem entit: 716 (454 album, 35 label, 135 rapper, 92 zanr)
// ═══════════════════════════════════════════════════════════════

import type { InterlinkEntity } from './remark-interlinking'

export const ENTITY_REGISTRY: InterlinkEntity[] = [
  {
    "name": "[Gudlak]",
    "slug": "gudlak",
    "type": "album"
  },
  {
    "name": "*PATTERN*",
    "slug": "pattern",
    "type": "album"
  },
  {
    "name": "#VELALASKY",
    "slug": "velalasky",
    "type": "album"
  },
  {
    "name": "1000",
    "slug": "1000",
    "type": "album"
  },
  {
    "name": "100RY",
    "slug": "100ry",
    "type": "album"
  },
  {
    "name": "111",
    "slug": "111",
    "type": "album"
  },
  {
    "name": "2 MOUCHY 1 RANOU",
    "slug": "2-mouchy-1-ranou",
    "type": "album"
  },
  {
    "name": "20.8. (Hudba z Hora)",
    "slug": "20-8-hudba-z-hora",
    "type": "album"
  },
  {
    "name": "2051",
    "slug": "2051",
    "type": "album"
  },
  {
    "name": "311",
    "slug": "311",
    "type": "album"
  },
  {
    "name": "33",
    "slug": "33",
    "type": "album"
  },
  {
    "name": "4 (Deluxe)",
    "slug": "4",
    "type": "album"
  },
  {
    "name": "58 tape vol. 1",
    "slug": "58-tape-vol-1",
    "type": "album"
  },
  {
    "name": "58 tape vol. 2",
    "slug": "58-tape-vol-2",
    "type": "album"
  },
  {
    "name": "7",
    "slug": "7",
    "type": "album"
  },
  {
    "name": "713",
    "slug": "713",
    "type": "album"
  },
  {
    "name": "9 Years of Moan Part 2",
    "slug": "9-years-of-moan-part-2",
    "type": "album"
  },
  {
    "name": "9EVET",
    "slug": "9evet",
    "type": "album"
  },
  {
    "name": "ABLETON JUNIOR!!!",
    "slug": "ableton-junior",
    "type": "album"
  },
  {
    "name": "Ach Ano III: Ballerbyn",
    "slug": "ach-ano-iii-ballerbyn",
    "type": "album"
  },
  {
    "name": "Ach Ano Mixtape",
    "slug": "ach-ano-mixtape",
    "type": "album"
  },
  {
    "name": "Airon Meidan",
    "slug": "airon-meidan",
    "type": "album"
  },
  {
    "name": "Album Naozaj Naživo",
    "slug": "album-naozaj-nazivo",
    "type": "album"
  },
  {
    "name": "Album Naozaj Naživo 2",
    "slug": "album-naozaj-nazivo-2",
    "type": "album"
  },
  {
    "name": "ALIEN",
    "slug": "alien",
    "type": "album"
  },
  {
    "name": "ALIEN: Expansion Pack",
    "slug": "alien-expansion-pack",
    "type": "album"
  },
  {
    "name": "Alliwant Wax digital 001 VA",
    "slug": "alliwant-wax-digital-001-va",
    "type": "album"
  },
  {
    "name": "Alliwant Wax digital 002",
    "slug": "alliwant-wax-digital-002",
    "type": "album"
  },
  {
    "name": "Alliwant Wax digital 010",
    "slug": "alliwant-wax-digital-010",
    "type": "album"
  },
  {
    "name": "Amonit (Deluxe)",
    "slug": "amonit",
    "type": "album"
  },
  {
    "name": "Antarktida",
    "slug": "antarktida",
    "type": "album"
  },
  {
    "name": "Arches of Scars",
    "slug": "arches-of-scars",
    "type": "album"
  },
  {
    "name": "Archive",
    "slug": "archive",
    "type": "album"
  },
  {
    "name": "Atlantída",
    "slug": "atlantida",
    "type": "album"
  },
  {
    "name": "Aura",
    "slug": "aura",
    "type": "album"
  },
  {
    "name": "Autotune AF",
    "slug": "autotune-af",
    "type": "album"
  },
  {
    "name": "Autotune AF 2",
    "slug": "autotune-af-2",
    "type": "album"
  },
  {
    "name": "Avec Moi",
    "slug": "avec-moi",
    "type": "album"
  },
  {
    "name": "Avec Moi (Kevin McKay Remix)",
    "slug": "avec-moi-kevin-mckay-remix",
    "type": "album"
  },
  {
    "name": "Babushka Traphouse",
    "slug": "babushka-traphouse",
    "type": "album"
  },
  {
    "name": "Babushka Traphouse afterparty",
    "slug": "babushka-traphouse-afterparty",
    "type": "album"
  },
  {
    "name": "Backwoods Bred",
    "slug": "backwoods-bred",
    "type": "album"
  },
  {
    "name": "Banan",
    "slug": "banan",
    "type": "album"
  },
  {
    "name": "Bandana",
    "slug": "bandana",
    "type": "album"
  },
  {
    "name": "Bauch Money II",
    "slug": "bauch-money-ii",
    "type": "album"
  },
  {
    "name": "BeastMode",
    "slug": "beastmode",
    "type": "album"
  },
  {
    "name": "Beat Tape 1",
    "slug": "beat-tape-1",
    "type": "album"
  },
  {
    "name": "Beat Tape 2",
    "slug": "beat-tape-2",
    "type": "album"
  },
  {
    "name": "before FUTUREPUNK",
    "slug": "before-futurepunk",
    "type": "album"
  },
  {
    "name": "Bengoro",
    "slug": "bengoro",
    "type": "album"
  },
  {
    "name": "Bengoro II",
    "slug": "bengoro-ii",
    "type": "album"
  },
  {
    "name": "BENİM",
    "slug": "benim",
    "type": "album"
  },
  {
    "name": "Berserk",
    "slug": "berserk",
    "type": "album"
  },
  {
    "name": "Best Of",
    "slug": "best-of",
    "type": "album"
  },
  {
    "name": "Better Ways",
    "slug": "better-ways",
    "type": "album"
  },
  {
    "name": "Bieber Fever",
    "slug": "bieber-fever",
    "type": "album"
  },
  {
    "name": "Bieber Fever Tour Life",
    "slug": "bieber-fever-tour-life",
    "type": "album"
  },
  {
    "name": "Black Chinese II",
    "slug": "black-chinese-ii",
    "type": "album"
  },
  {
    "name": "Bombím",
    "slug": "bombim",
    "type": "album"
  },
  {
    "name": "Boomerang",
    "slug": "boomerang",
    "type": "album"
  },
  {
    "name": "Brooklyn International",
    "slug": "brooklyn-international",
    "type": "album"
  },
  {
    "name": "Budapešť",
    "slug": "budapest",
    "type": "album"
  },
  {
    "name": "Buldozér",
    "slug": "buldozer",
    "type": "album"
  },
  {
    "name": "C.W.A",
    "slug": "c-w-a",
    "type": "album"
  },
  {
    "name": "CA$HFLOW",
    "slug": "ca-hflow",
    "type": "album"
  },
  {
    "name": "Celebrate Life (feat. Jeremy Carr)",
    "slug": "celebrate-life-feat-jeremy-carr",
    "type": "album"
  },
  {
    "name": "Celibát",
    "slug": "celibat",
    "type": "album"
  },
  {
    "name": "Cestovní horečka 03: Rome",
    "slug": "cestovni-horecka-03-rome",
    "type": "album"
  },
  {
    "name": "Cestovní horečka 04: Oslo",
    "slug": "cestovni-horecka-04-oslo",
    "type": "album"
  },
  {
    "name": "Cestovní horečka 05: Lisbon",
    "slug": "cestovni-horecka-05-lisbon",
    "type": "album"
  },
  {
    "name": "Cestovní horečka 06: Tokyoto",
    "slug": "cestovni-horecka-06-tokyoto",
    "type": "album"
  },
  {
    "name": "Cestovní horečka 07: French Polynesia",
    "slug": "cestovni-horecka-07-french-polynesia",
    "type": "album"
  },
  {
    "name": "Cestovní horečka 08: New York",
    "slug": "cestovni-horecka-08-new-york",
    "type": "album"
  },
  {
    "name": "Cestovní horečka 09: Rio de Janeiro",
    "slug": "cestovni-horecka-09-rio-de-janeiro",
    "type": "album"
  },
  {
    "name": "Cestovní horečka 10: Australia",
    "slug": "cestovni-horecka-10-australia",
    "type": "album"
  },
  {
    "name": "Cestovní horečka 11: Havana",
    "slug": "cestovni-horecka-11-havana",
    "type": "album"
  },
  {
    "name": "City Park",
    "slug": "city-park",
    "type": "album"
  },
  {
    "name": "CityLights",
    "slug": "citylights",
    "type": "album"
  },
  {
    "name": "Close To Me EP",
    "slug": "close-to-me-ep",
    "type": "album"
  },
  {
    "name": "COLD HEART HUSTLA",
    "slug": "cold-heart-hustla",
    "type": "album"
  },
  {
    "name": "CORRETTO 2",
    "slug": "corretto-2",
    "type": "album"
  },
  {
    "name": "Cowboys & Dreamers",
    "slug": "cowboys-dreamers",
    "type": "album"
  },
  {
    "name": "Což takhle dát si Tesař",
    "slug": "coz-takhle-dat-si-tesar",
    "type": "album"
  },
  {
    "name": "Crazy Horse",
    "slug": "crazy-horse",
    "type": "album"
  },
  {
    "name": "Crimson Stain",
    "slug": "crimson-stain",
    "type": "album"
  },
  {
    "name": "ČERNÁ VRÁNA",
    "slug": "cerna-vrana",
    "type": "album"
  },
  {
    "name": "Černej kůň",
    "slug": "cernej-kun",
    "type": "album"
  },
  {
    "name": "Černej kůň plus",
    "slug": "cernej-kun-plus",
    "type": "album"
  },
  {
    "name": "Černobílej svět",
    "slug": "cernobilej-svet",
    "type": "album"
  },
  {
    "name": "ČERTO",
    "slug": "certo",
    "type": "album"
  },
  {
    "name": "D1",
    "slug": "d1",
    "type": "album"
  },
  {
    "name": "D2",
    "slug": "d2",
    "type": "album"
  },
  {
    "name": "Daleko blíž",
    "slug": "daleko-bliz",
    "type": "album"
  },
  {
    "name": "Dance for You",
    "slug": "dance-for-you",
    "type": "album"
  },
  {
    "name": "DANK",
    "slug": "dank",
    "type": "album"
  },
  {
    "name": "DARKSIDE FANATIC",
    "slug": "darkside-fanatic",
    "type": "album"
  },
  {
    "name": "Dead Man Walking",
    "slug": "dead-man-walking",
    "type": "album"
  },
  {
    "name": "Def Jam World Tour: WARSAW",
    "slug": "def-jam-world-tour-warsaw",
    "type": "album"
  },
  {
    "name": "Definice Rapu",
    "slug": "definice-rapu",
    "type": "album"
  },
  {
    "name": "Demo",
    "slug": "demo",
    "type": "album"
  },
  {
    "name": "Desert Walk (feat. Outlandish)",
    "slug": "desert-walk-feat-outlandish",
    "type": "album"
  },
  {
    "name": "Detektor",
    "slug": "detektor",
    "type": "album"
  },
  {
    "name": "Detektor II",
    "slug": "detektor-ii",
    "type": "album"
  },
  {
    "name": "Detektor III",
    "slug": "detektor-iii",
    "type": "album"
  },
  {
    "name": "Diamant",
    "slug": "diamant",
    "type": "album"
  },
  {
    "name": "Different Time",
    "slug": "different-time",
    "type": "album"
  },
  {
    "name": "Diktátor",
    "slug": "diktator",
    "type": "album"
  },
  {
    "name": "Dimitto (Let Go) (feat. Bjørnskov)",
    "slug": "dimitto-let-go-feat-bj-rnskov",
    "type": "album"
  },
  {
    "name": "DISTURBIA",
    "slug": "disturbia",
    "type": "album"
  },
  {
    "name": "DJ Wich",
    "slug": "dj-wich",
    "type": "album"
  },
  {
    "name": "DJ Wich v Kontře",
    "slug": "dj-wich-v-kontra",
    "type": "album"
  },
  {
    "name": "Dlouhej příběh, krátkej svět",
    "slug": "dlouhej-pribeh-kratkej-svet",
    "type": "album"
  },
  {
    "name": "Dobrá duše, srdce ze zlata",
    "slug": "dobra-duse-srdce-ze-zlata",
    "type": "album"
  },
  {
    "name": "Doggin em",
    "slug": "doggin-em",
    "type": "album"
  },
  {
    "name": "Domáce Práce",
    "slug": "domace-prace",
    "type": "album"
  },
  {
    "name": "Don't Stop This Feeling",
    "slug": "don-t-stop-this-feeling",
    "type": "album"
  },
  {
    "name": "Don't Tell The Truth",
    "slug": "don-t-tell-the-truth",
    "type": "album"
  },
  {
    "name": "DONE",
    "slug": "done",
    "type": "album"
  },
  {
    "name": "DOWN4LIFE",
    "slug": "down4life",
    "type": "album"
  },
  {
    "name": "Drag4Hard",
    "slug": "drag4hard",
    "type": "album"
  },
  {
    "name": "DRIPOLAR",
    "slug": "dripolar",
    "type": "album"
  },
  {
    "name": "Dropbox",
    "slug": "dropbox",
    "type": "album"
  },
  {
    "name": "E.T.",
    "slug": "e-t",
    "type": "album"
  },
  {
    "name": "Ego 3",
    "slug": "ego-3",
    "type": "album"
  },
  {
    "name": "Ep Co Sa Vola Ep",
    "slug": "ep-co-sa-vola-ep",
    "type": "album"
  },
  {
    "name": "EP01",
    "slug": "ep01",
    "type": "album"
  },
  {
    "name": "Etc",
    "slug": "etc",
    "type": "album"
  },
  {
    "name": "EU Got Talent Vol.1",
    "slug": "eu-got-talent-vol-1",
    "type": "album"
  },
  {
    "name": "Every Night EP",
    "slug": "every-night-ep",
    "type": "album"
  },
  {
    "name": "F4R4on",
    "slug": "f4r4on",
    "type": "album"
  },
  {
    "name": "Fade In",
    "slug": "fade-in",
    "type": "album"
  },
  {
    "name": "Fade In (Instrumental)",
    "slug": "fade-in-instrumental",
    "type": "album"
  },
  {
    "name": "Falsetto Diamant",
    "slug": "falsetto-diamant",
    "type": "album"
  },
  {
    "name": "Fatamorgana",
    "slug": "fatamorgana",
    "type": "album"
  },
  {
    "name": "Fatte No More",
    "slug": "fatte-no-more",
    "type": "album"
  },
  {
    "name": "Feel The Groove EP",
    "slug": "feel-the-groove-ep",
    "type": "album"
  },
  {
    "name": "Feels Good",
    "slug": "feels-good",
    "type": "album"
  },
  {
    "name": "Femina",
    "slug": "femina",
    "type": "album"
  },
  {
    "name": "Fenomen",
    "slug": "fenomen",
    "type": "album"
  },
  {
    "name": "FIFA STREET",
    "slug": "fifa-street",
    "type": "album"
  },
  {
    "name": "Fight",
    "slug": "fight",
    "type": "album"
  },
  {
    "name": "Figury",
    "slug": "figury",
    "type": "album"
  },
  {
    "name": "Finding Myself",
    "slug": "finding-myself",
    "type": "album"
  },
  {
    "name": "Finesa",
    "slug": "finesa",
    "type": "album"
  },
  {
    "name": "FLEX SYMBOL",
    "slug": "flex-symbol",
    "type": "album"
  },
  {
    "name": "Flowdemort",
    "slug": "flowdemort",
    "type": "album"
  },
  {
    "name": "French Connection / Music Is the Future",
    "slug": "french-connection-music-is-the-future",
    "type": "album"
  },
  {
    "name": "FRÍ DOM",
    "slug": "fri-dom",
    "type": "album"
  },
  {
    "name": "FTS",
    "slug": "fts",
    "type": "album"
  },
  {
    "name": "FUTUREPUNK",
    "slug": "futurepunk",
    "type": "album"
  },
  {
    "name": "G.A.S.R",
    "slug": "g-a-s-r",
    "type": "album"
  },
  {
    "name": "G.O.A.T.",
    "slug": "g-o-a-t",
    "type": "album"
  },
  {
    "name": "Get Down Ep",
    "slug": "get-down-ep",
    "type": "album"
  },
  {
    "name": "Go Get It (feat. Rasco)",
    "slug": "go-get-it-feat-rasco",
    "type": "album"
  },
  {
    "name": "GoldCigo",
    "slug": "goldcigo",
    "type": "album"
  },
  {
    "name": "Golden Hour",
    "slug": "golden-hour",
    "type": "album"
  },
  {
    "name": "Goldkid",
    "slug": "goldkid",
    "type": "album"
  },
  {
    "name": "GOLDKID: ULTIMATE SECTION",
    "slug": "goldkid-ultimate-section",
    "type": "album"
  },
  {
    "name": "GoldKiid",
    "slug": "goldkiid",
    "type": "album"
  },
  {
    "name": "Good Night",
    "slug": "good-night",
    "type": "album"
  },
  {
    "name": "Goodfellas",
    "slug": "goodfellas",
    "type": "album"
  },
  {
    "name": "Gorila vs. Architekt",
    "slug": "gorila-vs-architekt",
    "type": "album"
  },
  {
    "name": "Gril Styl",
    "slug": "gril-styl",
    "type": "album"
  },
  {
    "name": "Guestlist",
    "slug": "guestlist",
    "type": "album"
  },
  {
    "name": "Harant",
    "slug": "harant",
    "type": "album"
  },
  {
    "name": "He Is Mine",
    "slug": "he-is-mine",
    "type": "album"
  },
  {
    "name": "Heartbeat",
    "slug": "heartbeat",
    "type": "album"
  },
  {
    "name": "HELLO",
    "slug": "hello",
    "type": "album"
  },
  {
    "name": "Hello Ibiza",
    "slug": "hello-ibiza",
    "type": "album"
  },
  {
    "name": "High Life",
    "slug": "high-life",
    "type": "album"
  },
  {
    "name": "Highs & Lows",
    "slug": "highs-lows",
    "type": "album"
  },
  {
    "name": "HOLLYMOOD mixtape",
    "slug": "hollymood-mixtape",
    "type": "album"
  },
  {
    "name": "Holy Labello",
    "slug": "holy-labello",
    "type": "album"
  },
  {
    "name": "Hood Celebrity 2",
    "slug": "hood-celebrity-2",
    "type": "album"
  },
  {
    "name": "Hood Celebrity 3",
    "slug": "hood-celebrity-3",
    "type": "album"
  },
  {
    "name": "Horizonty",
    "slug": "horizonty",
    "type": "album"
  },
  {
    "name": "HRA1",
    "slug": "hra1",
    "type": "album"
  },
  {
    "name": "Hráč Roku Playlist",
    "slug": "hrac-roku-playlist",
    "type": "album"
  },
  {
    "name": "Hrozny Hněvu",
    "slug": "hrozny-hnevu",
    "type": "album"
  },
  {
    "name": "Chimera Pt. 3",
    "slug": "chimera-pt-3",
    "type": "album"
  },
  {
    "name": "I",
    "slug": "i",
    "type": "album"
  },
  {
    "name": "I Can't Get You EP",
    "slug": "i-can-t-get-you-ep",
    "type": "album"
  },
  {
    "name": "I Giagia Mou Mageirevei Oneira Tiganita",
    "slug": "i-giagia-mou-mageirevei-oneira-tiganita",
    "type": "album"
  },
  {
    "name": "I Love",
    "slug": "i-love",
    "type": "album"
  },
  {
    "name": "I'm In Love (feat. Shontelle)",
    "slug": "i-m-in-love-feat-shontelle",
    "type": "album"
  },
  {
    "name": "I'm Sorry feat. Ledniczky",
    "slug": "i-m-sorry-feat-ledniczky",
    "type": "album"
  },
  {
    "name": "Idea x Strýc Nory EP",
    "slug": "idea-x-stryc-nory-ep",
    "type": "album"
  },
  {
    "name": "Idea x TrashBoySony EP",
    "slug": "idea-x-trashboysony-ep",
    "type": "album"
  },
  {
    "name": "Idiot",
    "slug": "idiot",
    "type": "album"
  },
  {
    "name": "IF",
    "slug": "if",
    "type": "album"
  },
  {
    "name": "II",
    "slug": "ii",
    "type": "album"
  },
  {
    "name": "Ilegal Mixtejp",
    "slug": "ilegal-mixtejp",
    "type": "album"
  },
  {
    "name": "Imaginarium naprosto běžných podivností",
    "slug": "imaginarium-naprosto-beznych-podivnosti",
    "type": "album"
  },
  {
    "name": "INTERREGNUM: Opus Magnum 2",
    "slug": "interregnum-opus-magnum-2",
    "type": "album"
  },
  {
    "name": "It's Ak!",
    "slug": "it-s-ak",
    "type": "album"
  },
  {
    "name": "J. EDEN E-G3N (#freekarlo edition)",
    "slug": "j-eden-e-g3n",
    "type": "album"
  },
  {
    "name": "J.Eden",
    "slug": "j-eden",
    "type": "album"
  },
  {
    "name": "J.Eden Dva",
    "slug": "j-eden-dva",
    "type": "album"
  },
  {
    "name": "J.Eden E-Gen",
    "slug": "j-eden-e-gen-mixed-by-nobodylisten",
    "type": "album"
  },
  {
    "name": "Jeden",
    "slug": "jeden",
    "type": "album"
  },
  {
    "name": "Jediný čo hreší",
    "slug": "jediny-co-hresi",
    "type": "album"
  },
  {
    "name": "JUSTiCE44 (Ledová Cesta)",
    "slug": "justice44-ledova-cesta",
    "type": "album"
  },
  {
    "name": "JUSTiCE44 (Mixtape1)",
    "slug": "justice44-mixtape1",
    "type": "album"
  },
  {
    "name": "Kapitán Láska (Deluxe Edition)",
    "slug": "kapitan-laska",
    "type": "album"
  },
  {
    "name": "KARAKORAM DLC",
    "slug": "karakoram-dlc",
    "type": "album"
  },
  {
    "name": "KARANTENA PARTY",
    "slug": "karantena-party",
    "type": "album"
  },
  {
    "name": "Keep on Lovin' Me",
    "slug": "keep-on-lovin-me",
    "type": "album"
  },
  {
    "name": "Khumba",
    "slug": "khumba",
    "type": "album"
  },
  {
    "name": "Kila Zdarma (Mixtape)",
    "slug": "kila-zdarma-mixtape",
    "type": "album"
  },
  {
    "name": "KINGPIN",
    "slug": "kingpin",
    "type": "album"
  },
  {
    "name": "KLOBUK DOLE",
    "slug": "klobuk-dole",
    "type": "album"
  },
  {
    "name": "KONEXIA",
    "slug": "konexia",
    "type": "album"
  },
  {
    "name": "Koupili jsme Boha, aby za nás makal",
    "slug": "koupili-jsme-boha-aby-za-nas-makal",
    "type": "album"
  },
  {
    "name": "Král",
    "slug": "kral",
    "type": "album"
  },
  {
    "name": "Krstný Otec",
    "slug": "krstny-otec",
    "type": "album"
  },
  {
    "name": "Krtek Forever",
    "slug": "krtek-forever",
    "type": "album"
  },
  {
    "name": "KRTEK MONEY LIFE",
    "slug": "krtek-money-life",
    "type": "album"
  },
  {
    "name": "Kruhy & Vlny",
    "slug": "kruhy-vlny",
    "type": "album"
  },
  {
    "name": "Kruhy a vlny",
    "slug": "kruhy-a-vlny",
    "type": "album"
  },
  {
    "name": "La Farándula",
    "slug": "la-farandula",
    "type": "album"
  },
  {
    "name": "LA HAINE",
    "slug": "la-haine",
    "type": "album"
  },
  {
    "name": "Láska Je Cool",
    "slug": "laska-je-cool",
    "type": "album"
  },
  {
    "name": "Legální drogy",
    "slug": "legalni-drogy",
    "type": "album"
  },
  {
    "name": "Let Me Tell You",
    "slug": "let-me-tell-you",
    "type": "album"
  },
  {
    "name": "Limit",
    "slug": "limit",
    "type": "album"
  },
  {
    "name": "Live @ O2 arena Praha",
    "slug": "live-o2-arena-praha",
    "type": "album"
  },
  {
    "name": "LOCKDOWN MUSIC",
    "slug": "lockdown-music",
    "type": "album"
  },
  {
    "name": "Lonely",
    "slug": "lonely",
    "type": "album"
  },
  {
    "name": "Luvv me",
    "slug": "luvv-me",
    "type": "album"
  },
  {
    "name": "Lyrika",
    "slug": "lyrika",
    "type": "album"
  },
  {
    "name": "Maison Maniak",
    "slug": "maison-maniak",
    "type": "album"
  },
  {
    "name": "Make It Hot",
    "slug": "make-it-hot",
    "type": "album"
  },
  {
    "name": "Making Country Music Cool Again",
    "slug": "making-country-music-cool-again",
    "type": "album"
  },
  {
    "name": "Malý Pepek Mixtape Vol. 1",
    "slug": "maly-pepek-mixtape-vol-1",
    "type": "album"
  },
  {
    "name": "Mám to",
    "slug": "mam-to",
    "type": "album"
  },
  {
    "name": "MAMUTI L.P.",
    "slug": "mamuti-l-p",
    "type": "album"
  },
  {
    "name": "Man of the Century",
    "slug": "man-of-the-century",
    "type": "album"
  },
  {
    "name": "Maniak Muzik",
    "slug": "maniak-muzik",
    "type": "album"
  },
  {
    "name": "ManTime",
    "slug": "mantime",
    "type": "album"
  },
  {
    "name": "Marko",
    "slug": "marko",
    "type": "album"
  },
  {
    "name": "Masterpiece",
    "slug": "masterpiece",
    "type": "album"
  },
  {
    "name": "Medusa",
    "slug": "medusa",
    "type": "album"
  },
  {
    "name": "Medusa II",
    "slug": "medusa-ii",
    "type": "album"
  },
  {
    "name": "Melanž",
    "slug": "melanz",
    "type": "album"
  },
  {
    "name": "Menaces & Opportunités",
    "slug": "menaces-opportunites",
    "type": "album"
  },
  {
    "name": "Mezi prsty",
    "slug": "mezi-prsty",
    "type": "album"
  },
  {
    "name": "Mezitím",
    "slug": "mezitim",
    "type": "album"
  },
  {
    "name": "Milovaný",
    "slug": "milovany",
    "type": "album"
  },
  {
    "name": "Minimal",
    "slug": "minimal",
    "type": "album"
  },
  {
    "name": "Miss You",
    "slug": "miss-you",
    "type": "album"
  },
  {
    "name": "Moby Dick",
    "slug": "moby-dick",
    "type": "album"
  },
  {
    "name": "Molo",
    "slug": "molo",
    "type": "album"
  },
  {
    "name": "Molo II (Deluxe)",
    "slug": "molo-ii",
    "type": "album"
  },
  {
    "name": "Monology",
    "slug": "monology",
    "type": "album"
  },
  {
    "name": "Mozoly",
    "slug": "mozoly",
    "type": "album"
  },
  {
    "name": "Mr. Sergei B",
    "slug": "mr-sergei-b",
    "type": "album"
  },
  {
    "name": "Multi",
    "slug": "multi",
    "type": "album"
  },
  {
    "name": "Mumie",
    "slug": "mumie",
    "type": "album"
  },
  {
    "name": "MUSIC THERAPY",
    "slug": "music-therapy",
    "type": "album"
  },
  {
    "name": "N!KTO",
    "slug": "n-kto",
    "type": "album"
  },
  {
    "name": "N!KTO",
    "slug": "nikto",
    "type": "album"
  },
  {
    "name": "n5",
    "slug": "n5",
    "type": "album"
  },
  {
    "name": "Nadzemí",
    "slug": "nadzemi",
    "type": "album"
  },
  {
    "name": "NAHORU NA DNO",
    "slug": "nahoru-na-dno",
    "type": "album"
  },
  {
    "name": "Nas – Illmatic",
    "slug": "illmatic",
    "type": "album"
  },
  {
    "name": "Naspäť domov",
    "slug": "naspat-domov",
    "type": "album"
  },
  {
    "name": "Né produkt",
    "slug": "ne-produkt",
    "type": "album"
  },
  {
    "name": "Nech Rusa flexit EP",
    "slug": "nech-rusa-flexit-ep",
    "type": "album"
  },
  {
    "name": "Never Ever Ep",
    "slug": "never-ever-ep",
    "type": "album"
  },
  {
    "name": "Never Let U Go (feat. Snoop Dogg & Brandon Beal)",
    "slug": "never-let-u-go-feat-snoop-dogg-brandon-beal",
    "type": "album"
  },
  {
    "name": "Neviem",
    "slug": "neviem",
    "type": "album"
  },
  {
    "name": "NIBIRU",
    "slug": "nibiru",
    "type": "album"
  },
  {
    "name": "Nie som tu náhodou",
    "slug": "nie-som-tu-nahodou",
    "type": "album"
  },
  {
    "name": "Nirvana",
    "slug": "nirvana",
    "type": "album"
  },
  {
    "name": "No Album",
    "slug": "no-album",
    "type": "album"
  },
  {
    "name": "NO PHONE: ŽIVĚ (live)",
    "slug": "no-phone-zive-live",
    "type": "album"
  },
  {
    "name": "No Title",
    "slug": "no-title",
    "type": "album"
  },
  {
    "name": "No Words Needed",
    "slug": "no-words-needed",
    "type": "album"
  },
  {
    "name": "Noční Podnik",
    "slug": "nocni-podnik",
    "type": "album"
  },
  {
    "name": "Noční vidění",
    "slug": "nocni-videni",
    "type": "album"
  },
  {
    "name": "NOISE AT A FUNERAL",
    "slug": "noise-at-a-funeral",
    "type": "album"
  },
  {
    "name": "Nonstop",
    "slug": "nonstop",
    "type": "album"
  },
  {
    "name": "Nový človek",
    "slug": "novy-clovek",
    "type": "album"
  },
  {
    "name": "O beatech a lidech",
    "slug": "o-beatech-a-lidech",
    "type": "album"
  },
  {
    "name": "O beatech a remixech",
    "slug": "o-beatech-a-remixech",
    "type": "album"
  },
  {
    "name": "O duši",
    "slug": "o-dusi",
    "type": "album"
  },
  {
    "name": "O Rakvích A Lidech",
    "slug": "o-rakvich-a-lidech",
    "type": "album"
  },
  {
    "name": "Off Season",
    "slug": "off-season",
    "type": "album"
  },
  {
    "name": "OG",
    "slug": "og",
    "type": "album"
  },
  {
    "name": "OK",
    "slug": "ok",
    "type": "album"
  },
  {
    "name": "OneWay",
    "slug": "oneway",
    "type": "album"
  },
  {
    "name": "Opičí král vrací úder",
    "slug": "opici-kral-vraci-uder",
    "type": "album"
  },
  {
    "name": "Opus Magnum",
    "slug": "opus-magnum",
    "type": "album"
  },
  {
    "name": "Originál",
    "slug": "original",
    "type": "album"
  },
  {
    "name": "ORIGINES",
    "slug": "origines",
    "type": "album"
  },
  {
    "name": "Orikoule",
    "slug": "orikoule",
    "type": "album"
  },
  {
    "name": "P's A Love",
    "slug": "ps-a-love",
    "type": "album"
  },
  {
    "name": "Painkillers",
    "slug": "painkillers",
    "type": "album"
  },
  {
    "name": "Pancier",
    "slug": "pancier",
    "type": "album"
  },
  {
    "name": "Pár listov z roku 2009",
    "slug": "par-listov-z-roku-2009",
    "type": "album"
  },
  {
    "name": "Paranoia",
    "slug": "paranoia",
    "type": "album"
  },
  {
    "name": "Piedestal EP",
    "slug": "piedestal-ep",
    "type": "album"
  },
  {
    "name": "Pirát",
    "slug": "pirat",
    "type": "album"
  },
  {
    "name": "Pod vlivem",
    "slug": "pod-vlivem",
    "type": "album"
  },
  {
    "name": "Podla Seba",
    "slug": "podla-seba",
    "type": "album"
  },
  {
    "name": "PONYA",
    "slug": "ponya",
    "type": "album"
  },
  {
    "name": "POP",
    "slug": "pop",
    "type": "album"
  },
  {
    "name": "POPSTAR",
    "slug": "popstar",
    "type": "album"
  },
  {
    "name": "Posledný doberman",
    "slug": "posledny-doberman",
    "type": "album"
  },
  {
    "name": "Pouliční Ekonomická 3: Láska & Loyalita",
    "slug": "poulicni-ekonomicka-3-laska-loyalita",
    "type": "album"
  },
  {
    "name": "Pozvi ma, neprídem",
    "slug": "pozvi-ma-nepridem",
    "type": "album"
  },
  {
    "name": "Precedens",
    "slug": "precedens",
    "type": "album"
  },
  {
    "name": "Premiéra",
    "slug": "premiera",
    "type": "album"
  },
  {
    "name": "Produkt",
    "slug": "produkt",
    "type": "album"
  },
  {
    "name": "Progress",
    "slug": "progress",
    "type": "album"
  },
  {
    "name": "PROJEKT RŮZNEJCH STAVŮ",
    "slug": "projekt-ruznejch-stavu",
    "type": "album"
  },
  {
    "name": "Prozyum",
    "slug": "prozyum",
    "type": "album"
  },
  {
    "name": "Prozyum (Director's Cut)",
    "slug": "prozyum-director-s-cut",
    "type": "album"
  },
  {
    "name": "Příběhy",
    "slug": "pribehy",
    "type": "album"
  },
  {
    "name": "Puls",
    "slug": "puls",
    "type": "album"
  },
  {
    "name": "Rap",
    "slug": "rap",
    "type": "album"
  },
  {
    "name": "rap disco revoluce",
    "slug": "rap-disco-revoluce",
    "type": "album"
  },
  {
    "name": "RAPutačné Riziko",
    "slug": "raputacne-riziko",
    "type": "album"
  },
  {
    "name": "Receio Fantasma",
    "slug": "receio-fantasma",
    "type": "album"
  },
  {
    "name": "Red Card",
    "slug": "red-card",
    "type": "album"
  },
  {
    "name": "Reflex",
    "slug": "reflex",
    "type": "album"
  },
  {
    "name": "Rep",
    "slug": "rep",
    "type": "album"
  },
  {
    "name": "Rep, Vol. 1",
    "slug": "rep-vol-1",
    "type": "album"
  },
  {
    "name": "Rep, Vol. 2",
    "slug": "rep-vol-2",
    "type": "album"
  },
  {
    "name": "Reprezentuju",
    "slug": "reprezentuju",
    "type": "album"
  },
  {
    "name": "Rest in Euphoria",
    "slug": "rest-in-euphoria",
    "type": "album"
  },
  {
    "name": "Restart",
    "slug": "restart",
    "type": "album"
  },
  {
    "name": "RIOT",
    "slug": "riot",
    "type": "album"
  },
  {
    "name": "Road 2 Redemption",
    "slug": "road-2-redemption",
    "type": "album"
  },
  {
    "name": "ROADTRIP",
    "slug": "roadtrip",
    "type": "album"
  },
  {
    "name": "RODINA, LOVE & SPEV",
    "slug": "rodina-love-spev",
    "type": "album"
  },
  {
    "name": "Rodinnej Typ",
    "slug": "rodinnej-typ",
    "type": "album"
  },
  {
    "name": "Rok psa",
    "slug": "rok-psa",
    "type": "album"
  },
  {
    "name": "ROMEO",
    "slug": "romeo",
    "type": "album"
  },
  {
    "name": "ROOTS",
    "slug": "roots",
    "type": "album"
  },
  {
    "name": "Rýmy, Hudba A Boh",
    "slug": "rymy-hudba-a-boh",
    "type": "album"
  },
  {
    "name": "Řev",
    "slug": "rev",
    "type": "album"
  },
  {
    "name": "Sbohem Roxano",
    "slug": "sbohem-roxano",
    "type": "album"
  },
  {
    "name": "See you in the morning",
    "slug": "see-you-in-the-morning",
    "type": "album"
  },
  {
    "name": "Sequel of Momo",
    "slug": "sequel-of-momo",
    "type": "album"
  },
  {
    "name": "Série remixů",
    "slug": "dj-wich-remixy",
    "type": "album"
  },
  {
    "name": "Short Stories",
    "slug": "short-stories",
    "type": "album"
  },
  {
    "name": "Short Stories 2",
    "slug": "short-stories-2",
    "type": "album"
  },
  {
    "name": "Showtime",
    "slug": "showtime",
    "type": "album"
  },
  {
    "name": "Si zabil",
    "slug": "si-zabil",
    "type": "album"
  },
  {
    "name": "SILA",
    "slug": "sila",
    "type": "album"
  },
  {
    "name": "Sin Límite vol. 2",
    "slug": "sin-limite-vol-2",
    "type": "album"
  },
  {
    "name": "skibidi alpha wolf type shi ep",
    "slug": "skibidi-alpha-wolf-type-shi-ep",
    "type": "album"
  },
  {
    "name": "Slohy Iným",
    "slug": "slohy-inym",
    "type": "album"
  },
  {
    "name": "Slova",
    "slug": "slova",
    "type": "album"
  },
  {
    "name": "Somebody That I Used To Know",
    "slug": "somebody-that-i-used-to-know",
    "type": "album"
  },
  {
    "name": "Soundtrack",
    "slug": "soundtrack",
    "type": "album"
  },
  {
    "name": "Soundtrack (Instrumentals)",
    "slug": "soundtrack-instrumentals",
    "type": "album"
  },
  {
    "name": "Space Lopata",
    "slug": "space-lopata",
    "type": "album"
  },
  {
    "name": "Speakers On",
    "slug": "speakers-on",
    "type": "album"
  },
  {
    "name": "SRÁT NA TO KDO JE KRÁL",
    "slug": "srat-na-to-kdo-je-kral",
    "type": "album"
  },
  {
    "name": "Starship Oblivion",
    "slug": "starship-oblivion",
    "type": "album"
  },
  {
    "name": "Stastne a vesele",
    "slug": "stastne-a-vesele",
    "type": "album"
  },
  {
    "name": "Stejný místo, Nový boty",
    "slug": "stejny-misto-novy-boty",
    "type": "album"
  },
  {
    "name": "Stereo",
    "slug": "stereo",
    "type": "album"
  },
  {
    "name": "Stop Play",
    "slug": "stop-play",
    "type": "album"
  },
  {
    "name": "Straight Outta Sklep",
    "slug": "straight-outta-sklep",
    "type": "album"
  },
  {
    "name": "STRAŠNICKEJ 2EN",
    "slug": "strasnickej-2en",
    "type": "album"
  },
  {
    "name": "STRAŠNICKEJ SEN",
    "slug": "strasnickej-sen",
    "type": "album"
  },
  {
    "name": "StreamTape",
    "slug": "streamtape",
    "type": "album"
  },
  {
    "name": "StreamTape: Vítěznej oblouk",
    "slug": "streamtape-viteznej-oblouk",
    "type": "album"
  },
  {
    "name": "STREET HAMLET",
    "slug": "street-hamlet",
    "type": "album"
  },
  {
    "name": "Street Sermons, Vol. 1",
    "slug": "street-sermons-vol-1",
    "type": "album"
  },
  {
    "name": "Střepy",
    "slug": "strepy",
    "type": "album"
  },
  {
    "name": "SUPERNOVA",
    "slug": "supernova",
    "type": "album"
  },
  {
    "name": "Svědomí",
    "slug": "svedomi",
    "type": "album"
  },
  {
    "name": "Svět baví",
    "slug": "svet-bavi",
    "type": "album"
  },
  {
    "name": "Svět je náš",
    "slug": "svet-je-nas",
    "type": "album"
  },
  {
    "name": "Svetelný meč",
    "slug": "svetelny-mec",
    "type": "album"
  },
  {
    "name": "SWAG",
    "slug": "swag",
    "type": "album"
  },
  {
    "name": "SWAG SIDE STORY",
    "slug": "swag-side-story",
    "type": "album"
  },
  {
    "name": "SWITCHBLADES",
    "slug": "switchblades",
    "type": "album"
  },
  {
    "name": "Šťastné dieťa",
    "slug": "stastne-dieta",
    "type": "album"
  },
  {
    "name": "Tales Of A Necromancer",
    "slug": "tales-of-a-necromancer",
    "type": "album"
  },
  {
    "name": "Talkshow",
    "slug": "talkshow",
    "type": "album"
  },
  {
    "name": "Tango & Kouř",
    "slug": "tango-kour",
    "type": "album"
  },
  {
    "name": "Tažní ptáci",
    "slug": "tazni-ptaci",
    "type": "album"
  },
  {
    "name": "Tempo",
    "slug": "tempo",
    "type": "album"
  },
  {
    "name": "Tempo (Instrumental)",
    "slug": "tempo-instrumental",
    "type": "album"
  },
  {
    "name": "Teritorium I",
    "slug": "teritorium-i",
    "type": "album"
  },
  {
    "name": "Teritorium II",
    "slug": "teritorium-ii",
    "type": "album"
  },
  {
    "name": "Teritorium III.",
    "slug": "teritorium-iii",
    "type": "album"
  },
  {
    "name": "Teritorium Remixy",
    "slug": "teritorium-remixy",
    "type": "album"
  },
  {
    "name": "Tetris",
    "slug": "tetris",
    "type": "album"
  },
  {
    "name": "The Prodigal Son",
    "slug": "the-prodigal-son",
    "type": "album"
  },
  {
    "name": "The Text",
    "slug": "the-text",
    "type": "album"
  },
  {
    "name": "Through These Eyes",
    "slug": "through-these-eyes",
    "type": "album"
  },
  {
    "name": "THUG LOVE SOFIA",
    "slug": "thug-love-sofia",
    "type": "album"
  },
  {
    "name": "TILL I DIE",
    "slug": "till-i-die",
    "type": "album"
  },
  {
    "name": "TIMBERLAKETRAPPED",
    "slug": "timberlaketrapped",
    "type": "album"
  },
  {
    "name": "TIMBERLAKETRAPPED 2",
    "slug": "timberlaketrapped-2",
    "type": "album"
  },
  {
    "name": "To je vražda, napsal",
    "slug": "to-je-vrazda-napsal",
    "type": "album"
  },
  {
    "name": "Top",
    "slug": "top",
    "type": "album"
  },
  {
    "name": "Top Threat",
    "slug": "top-threat",
    "type": "album"
  },
  {
    "name": "TopProdukt",
    "slug": "topprodukt",
    "type": "album"
  },
  {
    "name": "Topství",
    "slug": "topstvi",
    "type": "album"
  },
  {
    "name": "TOXIC RODEO",
    "slug": "toxic-rodeo",
    "type": "album"
  },
  {
    "name": "TRAPOHORY",
    "slug": "trapohory",
    "type": "album"
  },
  {
    "name": "Trueself",
    "slug": "trueself",
    "type": "album"
  },
  {
    "name": "Třetí oko",
    "slug": "treti-oko",
    "type": "album"
  },
  {
    "name": "Tvoj tatko",
    "slug": "tvoj-tatko",
    "type": "album"
  },
  {
    "name": "Ultra! Ultra!",
    "slug": "ultra-ultra",
    "type": "album"
  },
  {
    "name": "Umění žít",
    "slug": "umeni-zit",
    "type": "album"
  },
  {
    "name": "Umenie žiť",
    "slug": "umenie-zit",
    "type": "album"
  },
  {
    "name": "Unplugged | 2004-2014",
    "slug": "unplugged-2004-2014",
    "type": "album"
  },
  {
    "name": "Utržený sluchátko / Puma",
    "slug": "utrzeny-sluchatko-puma",
    "type": "album"
  },
  {
    "name": "Užívám Si To",
    "slug": "uzivam-si-to",
    "type": "album"
  },
  {
    "name": "v gastru nejsou lidi",
    "slug": "v-gastru-nejsou-lidi",
    "type": "album"
  },
  {
    "name": "V hlavní roli",
    "slug": "v-hlavni-roli",
    "type": "album"
  },
  {
    "name": "V pekle raj",
    "slug": "v-pekle-raj",
    "type": "album"
  },
  {
    "name": "Vamp love story",
    "slug": "vamp-love-story",
    "type": "album"
  },
  {
    "name": "Velký hry",
    "slug": "velke-hry",
    "type": "album"
  },
  {
    "name": "Víc než hudba",
    "slug": "vic-nez-hudba",
    "type": "album"
  },
  {
    "name": "Vis Major Mixtape",
    "slug": "vis-major-mixtape",
    "type": "album"
  },
  {
    "name": "Vítej mezi náma (NobodyListen Remix)",
    "slug": "vitej-mezi-nama-nobodylisten-remix",
    "type": "album"
  },
  {
    "name": "Vítr, déšť a slunce.",
    "slug": "vitr-dest-a-slunce",
    "type": "album"
  },
  {
    "name": "VOILÀ",
    "slug": "voila",
    "type": "album"
  },
  {
    "name": "Vyšehrad DVJE (Soundtrack)",
    "slug": "vysehrad-dvje-soundtrack",
    "type": "album"
  },
  {
    "name": "WAGWAN",
    "slug": "wagwan",
    "type": "album"
  },
  {
    "name": "Walking On EP",
    "slug": "walking-on-ep",
    "type": "album"
  },
  {
    "name": "Weekend EP",
    "slug": "weekend-ep",
    "type": "album"
  },
  {
    "name": "WELL DONE",
    "slug": "well-done",
    "type": "album"
  },
  {
    "name": "What's My Name",
    "slug": "what-s-my-name",
    "type": "album"
  },
  {
    "name": "White Boy",
    "slug": "white-boy",
    "type": "album"
  },
  {
    "name": "WRAP: SLATT CHAWO vs. VLAĎKYSYN",
    "slug": "wrap-slatt-chawo-vs-vladkysyn",
    "type": "album"
  },
  {
    "name": "Wygrałem EP",
    "slug": "wygra-em-ep",
    "type": "album"
  },
  {
    "name": "Yak Orol",
    "slug": "yak-orol",
    "type": "album"
  },
  {
    "name": "Young Guns 01.",
    "slug": "young-guns-01",
    "type": "album"
  },
  {
    "name": "Young Guns 03.",
    "slug": "young-guns-03",
    "type": "album"
  },
  {
    "name": "Ypsilon Black",
    "slug": "ypsilon-black",
    "type": "album"
  },
  {
    "name": "Ypsilon White",
    "slug": "ypsilon-white",
    "type": "album"
  },
  {
    "name": "Yzomandias",
    "slug": "yzomandias",
    "type": "album"
  },
  {
    "name": "Yzomandias II: Zpátky na svojí planetu",
    "slug": "zpatky-na-svoji-planetu",
    "type": "album"
  },
  {
    "name": "Yzotape",
    "slug": "yzotape",
    "type": "album"
  },
  {
    "name": "Za 5 Dvanáct",
    "slug": "za-5-dvanact",
    "type": "album"
  },
  {
    "name": "Ze dna",
    "slug": "ze-dna",
    "type": "album"
  },
  {
    "name": "Zhora vypadá všechno líp",
    "slug": "zhora-vypada-vsechno-lip",
    "type": "album"
  },
  {
    "name": "Zkušenosti",
    "slug": "zkusenosti",
    "type": "album"
  },
  {
    "name": "Zmiešané Pocity Mixtape",
    "slug": "zmiesane-pocity-mixtape",
    "type": "album"
  },
  {
    "name": "Znova a zas",
    "slug": "znova-a-zas",
    "type": "album"
  },
  {
    "name": "Zůstat silnej",
    "slug": "zustat-silnej",
    "type": "album"
  },
  {
    "name": "Žijeme len raz",
    "slug": "zijeme-len-raz",
    "type": "album"
  },
  {
    "name": "Živijó",
    "slug": "zivijo",
    "type": "album"
  },
  {
    "name": "Život A Smrt Alberta Hersche",
    "slug": "zivot-a-smrt-alberta-hersche",
    "type": "album"
  },
  {
    "name": "100K",
    "slug": "100k",
    "type": "label"
  },
  {
    "name": "1312 Records",
    "slug": "1312-records",
    "type": "label"
  },
  {
    "name": "415 02 Records",
    "slug": "415-02-records",
    "type": "label"
  },
  {
    "name": "44 Enterprise",
    "slug": "44-enterprise",
    "type": "label"
  },
  {
    "name": "Archetyp 51",
    "slug": "archetyp-51",
    "type": "label"
  },
  {
    "name": "Azurit Kingdom",
    "slug": "azurit-kingdom",
    "type": "label"
  },
  {
    "name": "Bigg Boss",
    "slug": "biggboss",
    "type": "label"
  },
  {
    "name": "BipolarSnowBlood",
    "slug": "bipolarsnowblood",
    "type": "label"
  },
  {
    "name": "Black Sheep Cartel",
    "slug": "black-sheep-cartel",
    "type": "label"
  },
  {
    "name": "Blakkwood Records",
    "slug": "blakkwood-records",
    "type": "label"
  },
  {
    "name": "BPM (Básníci před mikrofonem)",
    "slug": "bpm",
    "type": "label"
  },
  {
    "name": "Central Gang",
    "slug": "central-gang",
    "type": "label"
  },
  {
    "name": "Comebackgang",
    "slug": "comebackgang",
    "type": "label"
  },
  {
    "name": "Detektor Records",
    "slug": "detektor-records",
    "type": "label"
  },
  {
    "name": "Die Mannschaft",
    "slug": "die-mannschaft",
    "type": "label"
  },
  {
    "name": "Dvojlitrboyzz",
    "slug": "dvojlitrboyzz",
    "type": "label"
  },
  {
    "name": "Everydays",
    "slug": "everydays",
    "type": "label"
  },
  {
    "name": "F*CK THEM",
    "slug": "fuck-them",
    "type": "label"
  },
  {
    "name": "Fuerza Arma",
    "slug": "fuerza-arma",
    "type": "label"
  },
  {
    "name": "Golden Touch",
    "slug": "golden-touch",
    "type": "label"
  },
  {
    "name": "Hypno808",
    "slug": "hypno-808",
    "type": "label"
  },
  {
    "name": "Churaq Clique",
    "slug": "churaq-clique",
    "type": "label"
  },
  {
    "name": "L.U.Z.A.",
    "slug": "luza",
    "type": "label"
  },
  {
    "name": "Lavutaris Records",
    "slug": "lavutaris-records",
    "type": "label"
  },
  {
    "name": "Mike Roft Records",
    "slug": "mike-roft",
    "type": "label"
  },
  {
    "name": "Milion+",
    "slug": "milion-plus",
    "type": "label"
  },
  {
    "name": "Názov Stavby",
    "slug": "nazov-stavby",
    "type": "label"
  },
  {
    "name": "Pozor Records",
    "slug": "pozor-records",
    "type": "label"
  },
  {
    "name": "PVP Label",
    "slug": "pvp-label",
    "type": "label"
  },
  {
    "name": "Rychlí Kluci",
    "slug": "rychli-kluci",
    "type": "label"
  },
  {
    "name": "Skerocuda",
    "slug": "skerocuda",
    "type": "label"
  },
  {
    "name": "TroubleGang",
    "slug": "troublegang",
    "type": "label"
  },
  {
    "name": "TRUESELF RECORDS",
    "slug": "trueself-records",
    "type": "label"
  },
  {
    "name": "Ty Nikdy",
    "slug": "ty-nikdy",
    "type": "label"
  },
  {
    "name": "ZNK",
    "slug": "znk",
    "type": "label"
  },
  {
    "name": "58G",
    "slug": "58g",
    "type": "rapper"
  },
  {
    "name": "7krát3",
    "slug": "7krat3",
    "type": "rapper",
    "aliases": [
      "Štěpán Hebík"
    ]
  },
  {
    "name": "ADiss",
    "slug": "adiss",
    "type": "rapper",
    "aliases": [
      "Adam Miščík"
    ]
  },
  {
    "name": "Alan Murin",
    "slug": "alan-murin",
    "type": "rapper",
    "aliases": [
      "Sane"
    ]
  },
  {
    "name": "Annet X",
    "slug": "annet-x",
    "type": "rapper",
    "aliases": [
      "Anna Vodičková",
      "Annet"
    ]
  },
  {
    "name": "Arleta",
    "slug": "arleta",
    "type": "rapper",
    "aliases": [
      "Arleta Berndorff"
    ]
  },
  {
    "name": "AstralKid22",
    "slug": "astralkid22",
    "type": "rapper",
    "aliases": [
      "Neveřejné (údajně něco s ‚K‘)",
      "AK22",
      "Kid"
    ]
  },
  {
    "name": "Ben Cristovao",
    "slug": "ben-cristovao",
    "type": "rapper",
    "aliases": [
      "Ben da Silva Cristóvão",
      "Benny Cristo"
    ]
  },
  {
    "name": "Blako",
    "slug": "blako",
    "type": "rapper"
  },
  {
    "name": "Bobby Blaze",
    "slug": "bobby-blaze",
    "type": "rapper"
  },
  {
    "name": "CA$HANOVA BULHAR",
    "slug": "ca-hanova-bulhar",
    "type": "rapper",
    "aliases": [
      "Matěj Kratejl",
      "Cashanova Bulhar"
    ]
  },
  {
    "name": "Calin",
    "slug": "calin",
    "type": "rapper",
    "aliases": [
      "Călin Panfili"
    ]
  },
  {
    "name": "Čistychov",
    "slug": "cistychov",
    "type": "rapper",
    "aliases": [
      "Daniel Chládek",
      "Čis T",
      "DJ Danny Alves"
    ]
  },
  {
    "name": "D.Kop",
    "slug": "d-kop",
    "type": "rapper"
  },
  {
    "name": "Dalyb",
    "slug": "dalyb",
    "type": "rapper",
    "aliases": [
      "Dalibor Štofan"
    ]
  },
  {
    "name": "Dame",
    "slug": "dame",
    "type": "rapper",
    "aliases": [
      "Radek Prchal"
    ]
  },
  {
    "name": "Daniel Vardan",
    "slug": "daniel-vardan",
    "type": "rapper",
    "aliases": [
      "Daniel Pavliš"
    ]
  },
  {
    "name": "Dano Kapitán",
    "slug": "dano-kapitan",
    "type": "rapper"
  },
  {
    "name": "Dara Rolins",
    "slug": "dara-rolins",
    "type": "rapper",
    "aliases": [
      "Dara"
    ]
  },
  {
    "name": "DAREWIN",
    "slug": "darewin",
    "type": "rapper"
  },
  {
    "name": "David Beng Rostaš",
    "slug": "david-beng-rostas",
    "type": "rapper",
    "aliases": [
      "David Rostaš",
      "Beng",
      "Bengoro"
    ]
  },
  {
    "name": "Decky",
    "slug": "decky",
    "type": "rapper",
    "aliases": [
      "Jakub Decky",
      "Decky Beats"
    ]
  },
  {
    "name": "DEJV",
    "slug": "dejv",
    "type": "rapper",
    "aliases": [
      "David"
    ]
  },
  {
    "name": "DJ AKA",
    "slug": "dj-aka",
    "type": "rapper",
    "aliases": [
      "Adam Kavalír",
      "AKA"
    ]
  },
  {
    "name": "DJ Fatte",
    "slug": "dj-fatte",
    "type": "rapper",
    "aliases": [
      "Martin Fatka",
      "Fatte",
      "DJ Fatty"
    ]
  },
  {
    "name": "DJ Kadr",
    "slug": "dj-kadr",
    "type": "rapper"
  },
  {
    "name": "DJ Wich",
    "slug": "dj-wich",
    "type": "rapper",
    "aliases": [
      "Tomáš Karel",
      "Wich"
    ]
  },
  {
    "name": "Dokkeytino",
    "slug": "dokkeytino",
    "type": "rapper",
    "aliases": [
      "Ivan Oravec"
    ]
  },
  {
    "name": "Doktor601",
    "slug": "doktor601",
    "type": "rapper"
  },
  {
    "name": "Dollar Prync",
    "slug": "dollar-prync",
    "type": "rapper"
  },
  {
    "name": "Dorian",
    "slug": "dorian",
    "type": "rapper",
    "aliases": [
      "David Albrecht"
    ]
  },
  {
    "name": "Ego",
    "slug": "ego",
    "type": "rapper",
    "aliases": [
      "Michal Straka"
    ]
  },
  {
    "name": "Ektor",
    "slug": "ektor",
    "type": "rapper",
    "aliases": [
      "Marko Elefteriadis"
    ]
  },
  {
    "name": "Eris",
    "slug": "eris",
    "type": "rapper"
  },
  {
    "name": "Eusebio",
    "slug": "eusebio",
    "type": "rapper"
  },
  {
    "name": "Fobia Kid",
    "slug": "fobia-kid",
    "type": "rapper",
    "aliases": [
      "Mateus Mampouya"
    ]
  },
  {
    "name": "Forest Blunt",
    "slug": "forest-blunt",
    "type": "rapper"
  },
  {
    "name": "Fvck_Kvlt",
    "slug": "fvck-kvlt",
    "type": "rapper",
    "aliases": [
      "Denis Bango"
    ]
  },
  {
    "name": "G1nter",
    "slug": "g1nter",
    "type": "rapper",
    "aliases": [
      "Michal Günter"
    ]
  },
  {
    "name": "Gleb",
    "slug": "gleb",
    "type": "rapper",
    "aliases": [
      "Gleb Veselov"
    ]
  },
  {
    "name": "Grimaso",
    "slug": "grimaso",
    "type": "rapper"
  },
  {
    "name": "guapanova",
    "slug": "guapanova",
    "type": "rapper"
  },
  {
    "name": "H16",
    "slug": "h16",
    "type": "rapper"
  },
  {
    "name": "Hard Rico",
    "slug": "hard-rico",
    "type": "rapper",
    "aliases": [
      "Enrico Pešta"
    ]
  },
  {
    "name": "Hasan",
    "slug": "hasan",
    "type": "rapper",
    "aliases": [
      "Josef Andreas"
    ]
  },
  {
    "name": "Hugo Toxxx",
    "slug": "hugo-toxxx",
    "type": "rapper",
    "aliases": [
      "Jan Daněk"
    ]
  },
  {
    "name": "Humla",
    "slug": "humla",
    "type": "rapper"
  },
  {
    "name": "Chawo",
    "slug": "chawo",
    "type": "rapper"
  },
  {
    "name": "Chubeats",
    "slug": "chubeats",
    "type": "rapper"
  },
  {
    "name": "Idea",
    "slug": "idea",
    "type": "rapper",
    "aliases": [
      "Josef Změlík"
    ]
  },
  {
    "name": "Indy",
    "slug": "indy",
    "type": "rapper",
    "aliases": [
      "Andreas Christodoulou"
    ]
  },
  {
    "name": "Irit",
    "slug": "irit",
    "type": "rapper"
  },
  {
    "name": "James Cole",
    "slug": "james-cole",
    "type": "rapper",
    "aliases": [
      "Pavel Vrba"
    ]
  },
  {
    "name": "Jay Diesel",
    "slug": "jay-diesel",
    "type": "rapper",
    "aliases": [
      "Jiří Rejfíř"
    ]
  },
  {
    "name": "Jckpt",
    "slug": "jckpt",
    "type": "rapper"
  },
  {
    "name": "Jickson",
    "slug": "jickson",
    "type": "rapper",
    "aliases": [
      "Mathivendhan",
      "JCK",
      "Jackson"
    ]
  },
  {
    "name": "Kali",
    "slug": "kali",
    "type": "rapper",
    "aliases": [
      "Koloman Magyary"
    ]
  },
  {
    "name": "Kamil Hoffmann",
    "slug": "kamil-hoffmann",
    "type": "rapper",
    "aliases": [
      "Kamil",
      "KH",
      "Hoffmann"
    ]
  },
  {
    "name": "Karlo",
    "slug": "karlo",
    "type": "rapper",
    "aliases": [
      "Juraj Čaba",
      "Gumbgu"
    ]
  },
  {
    "name": "Katannah",
    "slug": "katannah",
    "type": "rapper",
    "aliases": [
      "Timothy Vanke"
    ]
  },
  {
    "name": "Katarzia",
    "slug": "katarzia",
    "type": "rapper"
  },
  {
    "name": "Kato",
    "slug": "kato",
    "type": "rapper",
    "aliases": [
      "Adam Svatoš",
      "Deph",
      "Defski"
    ]
  },
  {
    "name": "Kojo",
    "slug": "kojo",
    "type": "rapper",
    "aliases": [
      "William Mendonça Sachambula"
    ]
  },
  {
    "name": "Konex",
    "slug": "konex",
    "type": "rapper"
  },
  {
    "name": "Kup Kodein",
    "slug": "kup-kodein",
    "type": "rapper"
  },
  {
    "name": "Kvítek",
    "slug": "kvitek",
    "type": "rapper",
    "aliases": [
      "Libor Kvítek",
      "Kvítek z horroru"
    ]
  },
  {
    "name": "LA4",
    "slug": "la4",
    "type": "rapper",
    "aliases": [
      "Martin Somr"
    ]
  },
  {
    "name": "Labello",
    "slug": "labello",
    "type": "rapper",
    "aliases": [
      "Lukáš Labík",
      "Laba"
    ]
  },
  {
    "name": "Lipo",
    "slug": "lipo",
    "type": "rapper",
    "aliases": [
      "Jonáš Červinka"
    ]
  },
  {
    "name": "Loudz1",
    "slug": "loudz1",
    "type": "rapper",
    "aliases": [
      "Lukáš Loudil",
      "Loud",
      "Loud One"
    ]
  },
  {
    "name": "Luca Brassi10x",
    "slug": "luca-brassi10x",
    "type": "rapper",
    "aliases": [
      "Luka Mašulovič"
    ]
  },
  {
    "name": "Lvcas Dope",
    "slug": "lvcas-dope",
    "type": "rapper",
    "aliases": [
      "Lukas Çakmak (dříve Lukáš Navrátil)",
      "Lukas Çakmak",
      "Lukáš Navrátil"
    ]
  },
  {
    "name": "Magenta",
    "slug": "magenta",
    "type": "rapper"
  },
  {
    "name": "Majk Spirit",
    "slug": "majk-spirit",
    "type": "rapper",
    "aliases": [
      "Michal Dušička"
    ]
  },
  {
    "name": "MAKIN HOLLOV",
    "slug": "makin-hollov",
    "type": "rapper"
  },
  {
    "name": "Maniak",
    "slug": "maniak",
    "type": "rapper",
    "aliases": [
      "Jiří Veselý"
    ]
  },
  {
    "name": "Marger",
    "slug": "marger",
    "type": "rapper"
  },
  {
    "name": "Marpo",
    "slug": "marpo",
    "type": "rapper",
    "aliases": [
      "Martin Pavlík"
    ]
  },
  {
    "name": "Matej Straka",
    "slug": "matej-straka",
    "type": "rapper"
  },
  {
    "name": "MC Gey",
    "slug": "mc-gey",
    "type": "rapper",
    "aliases": [
      "Štěpán Gajdoš"
    ]
  },
  {
    "name": "MDMX",
    "slug": "mdmx",
    "type": "rapper"
  },
  {
    "name": "Meizyy / MEIZMEN",
    "slug": "mejzyy",
    "type": "rapper",
    "aliases": [
      "Matěj Dejdar"
    ]
  },
  {
    "name": "Michajlov",
    "slug": "michajlov",
    "type": "rapper"
  },
  {
    "name": "Mike Trafik",
    "slug": "mike-trafik",
    "type": "rapper",
    "aliases": [
      "Michal Hájek",
      "DJ Mike Trafik"
    ]
  },
  {
    "name": "Miky Mora",
    "slug": "miky-mora",
    "type": "rapper"
  },
  {
    "name": "MOMO",
    "slug": "momo",
    "type": "rapper"
  },
  {
    "name": "Mr Be",
    "slug": "mr-be",
    "type": "rapper"
  },
  {
    "name": "Nerieš",
    "slug": "neries",
    "type": "rapper"
  },
  {
    "name": "Nik Tendo",
    "slug": "nik-tendo",
    "type": "rapper",
    "aliases": [
      "Dominik Citta"
    ]
  },
  {
    "name": "OGmiaG",
    "slug": "ogmiag",
    "type": "rapper"
  },
  {
    "name": "Orion",
    "slug": "orion",
    "type": "rapper",
    "aliases": [
      "Petr Martínek"
    ]
  },
  {
    "name": "P T K",
    "slug": "ptk",
    "type": "rapper",
    "aliases": [
      "Patrik Aišman"
    ]
  },
  {
    "name": "Pain",
    "slug": "pain",
    "type": "rapper",
    "aliases": [
      "Vojtěch Krbec"
    ]
  },
  {
    "name": "Paulie Garand",
    "slug": "paulie-garand",
    "type": "rapper",
    "aliases": [
      "Pavel Harant"
    ]
  },
  {
    "name": "Peter Pann",
    "slug": "peter-pann",
    "type": "rapper"
  },
  {
    "name": "Pil C",
    "slug": "pil-c",
    "type": "rapper",
    "aliases": [
      "Lukáš Kajanovič"
    ]
  },
  {
    "name": "Prezident Lourajder",
    "slug": "prezident-lourajder",
    "type": "rapper"
  },
  {
    "name": "Psycho Rhyme",
    "slug": "psycho-rhyme",
    "type": "rapper"
  },
  {
    "name": "Redzed",
    "slug": "redzed",
    "type": "rapper"
  },
  {
    "name": "Refew",
    "slug": "refew",
    "type": "rapper",
    "aliases": [
      "Erik Gábor"
    ]
  },
  {
    "name": "Renne Dang",
    "slug": "renne-dang",
    "type": "rapper",
    "aliases": [
      "René Dang"
    ]
  },
  {
    "name": "Resetedh",
    "slug": "resetedh",
    "type": "rapper",
    "aliases": [
      "Adam Houšť"
    ]
  },
  {
    "name": "Rest",
    "slug": "rest",
    "type": "rapper",
    "aliases": [
      "Adam Chlpík"
    ]
  },
  {
    "name": "Robin Tent",
    "slug": "robin-tent",
    "type": "rapper",
    "aliases": [
      "Robin Stanka"
    ]
  },
  {
    "name": "Robin Zoot",
    "slug": "robin-zoot",
    "type": "rapper",
    "aliases": [
      "Robert Pouzar",
      "Zooty"
    ]
  },
  {
    "name": "Rytmus",
    "slug": "rytmus",
    "type": "rapper",
    "aliases": [
      "Patrik Vrbovský"
    ]
  },
  {
    "name": "Řezník",
    "slug": "reznik",
    "type": "rapper",
    "aliases": [
      "Martin Řezníček"
    ]
  },
  {
    "name": "Sakito",
    "slug": "sakito",
    "type": "rapper"
  },
  {
    "name": "Samey",
    "slug": "samey",
    "type": "rapper",
    "aliases": [
      "Samuel Chalupka",
      "Sameyko"
    ]
  },
  {
    "name": "Sara Rikas",
    "slug": "sara-rikas",
    "type": "rapper",
    "aliases": [
      "Sára Štoselová"
    ]
  },
  {
    "name": "Sebastian",
    "slug": "sebastian",
    "type": "rapper"
  },
  {
    "name": "Sensey",
    "slug": "sensey",
    "type": "rapper"
  },
  {
    "name": "Separ",
    "slug": "separ",
    "type": "rapper",
    "aliases": [
      "Michael Kmeť"
    ]
  },
  {
    "name": "Sergei Barracuda",
    "slug": "sergei-barracuda",
    "type": "rapper",
    "aliases": [
      "Erik Peter"
    ]
  },
  {
    "name": "Shaka CG",
    "slug": "shaka-cg",
    "type": "rapper"
  },
  {
    "name": "SHIMMI",
    "slug": "shimmi",
    "type": "rapper"
  },
  {
    "name": "Schyzo",
    "slug": "schyzo",
    "type": "rapper"
  },
  {
    "name": "SIMA",
    "slug": "sima",
    "type": "rapper"
  },
  {
    "name": "Smack One",
    "slug": "smack",
    "type": "rapper",
    "aliases": [
      "Jakub Janeček",
      "Smack"
    ]
  },
  {
    "name": "Sofian Medjmedj",
    "slug": "sofian-medjmedj",
    "type": "rapper",
    "aliases": [
      "Sofian"
    ]
  },
  {
    "name": "Stein27",
    "slug": "stein27",
    "type": "rapper",
    "aliases": [
      "Petr Adámek"
    ]
  },
  {
    "name": "Tafrob",
    "slug": "tafrob",
    "type": "rapper",
    "aliases": [
      "Pavel Sup"
    ]
  },
  {
    "name": "The Mag",
    "slug": "the-mag",
    "type": "rapper"
  },
  {
    "name": "Tina",
    "slug": "tina",
    "type": "rapper",
    "aliases": [
      "Martina Csillaghová"
    ]
  },
  {
    "name": "Tisci",
    "slug": "tisci",
    "type": "rapper"
  },
  {
    "name": "TK27",
    "slug": "tk27",
    "type": "rapper",
    "aliases": [
      "Tomáš Kučera"
    ]
  },
  {
    "name": "Vercetti CG",
    "slug": "vercetti-cg",
    "type": "rapper",
    "aliases": [
      "Dominik Vyšata"
    ]
  },
  {
    "name": "Viktor Sheen",
    "slug": "viktor-sheen",
    "type": "rapper",
    "aliases": [
      "Viktor Dundič"
    ]
  },
  {
    "name": "Vladimir 518",
    "slug": "vladimir-518",
    "type": "rapper",
    "aliases": [
      "Vladimír Brož"
    ]
  },
  {
    "name": "VlaďkySyn",
    "slug": "vladkysyn",
    "type": "rapper"
  },
  {
    "name": "Vojtaano",
    "slug": "vojtaano",
    "type": "rapper"
  },
  {
    "name": "Voodoo808",
    "slug": "voodoo808",
    "type": "rapper"
  },
  {
    "name": "Yzomandias",
    "slug": "yzomandias",
    "type": "rapper",
    "aliases": [
      "Jakub Vlček"
    ]
  },
  {
    "name": "Zayo",
    "slug": "zayo",
    "type": "rapper"
  },
  {
    "name": "Zuris",
    "slug": "zuris",
    "type": "rapper"
  },
  {
    "name": "Abstract Hip Hop",
    "slug": "abstract-hip-hop",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Academic Rap",
    "slug": "academic-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Afro Rap",
    "slug": "afro-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Afrobeats",
    "slug": "afrobeats",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Alternative Hip Hop",
    "slug": "alternative-hip-hop",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Alternative Rap",
    "slug": "alternative-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Ambient Rap",
    "slug": "ambient-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Art Rap",
    "slug": "art-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Bassline",
    "slug": "bassline",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Boom Bap",
    "slug": "boom-bap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Britský hip hop",
    "slug": "britsky-hip-hop",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Cloud Rap",
    "slug": "cloud-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Comedy Rap",
    "slug": "comedy-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Comic Book Rap",
    "slug": "comic-book-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Conceptual Rap",
    "slug": "conceptual-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Conscious Rap",
    "slug": "conscious-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Country Rap",
    "slug": "country-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Czech Pop",
    "slug": "czech-pop",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Czech Rap",
    "slug": "czech-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Dance Rap",
    "slug": "dance-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Dancehall",
    "slug": "dancehall",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Dark Rap",
    "slug": "dark-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Dark Trap",
    "slug": "dark-trap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Drill",
    "slug": "drill",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Drum and Bass",
    "slug": "drum-and-bass",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Drum and Bass (MC kultura)",
    "slug": "drum-and-bass-mc",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "East Coast Rap",
    "slug": "east-coast-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Electronic Rap",
    "slug": "electronic-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Emo rap",
    "slug": "emo-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Experimental Hip Hop",
    "slug": "experimental-hip-hop",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Experimental Rap",
    "slug": "experimental-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Experimental Trap",
    "slug": "experimental-trap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Freestyle Rap",
    "slug": "freestyle-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Gangsta Rap",
    "slug": "gangsta-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Garage Punk",
    "slug": "garage-punk",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Glitch Hop",
    "slug": "glitch-hop",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Gothic Rap",
    "slug": "gothic-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Grime",
    "slug": "grime",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Hardcore Punk",
    "slug": "hardcore-punk",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Hardcore Rap",
    "slug": "hardcore-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Hip-hop",
    "slug": "hip-hop",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Horrorcore",
    "slug": "horrorcore",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "House Rap",
    "slug": "house-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Jazz Rap",
    "slug": "jazz-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Jungle (MC kultura)",
    "slug": "jungle-mc",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Lo-Fi Rap",
    "slug": "lo-fi-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Lyrical Rap",
    "slug": "lyrical-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Mafioso Rap",
    "slug": "mafioso-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Mainstream Rap",
    "slug": "mainstream-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Melodic Rap",
    "slug": "melodic-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Melodic Trap",
    "slug": "melodic-trap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Modern Rap",
    "slug": "modern-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Mumble Rap",
    "slug": "mumble-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Mystical Rap",
    "slug": "mystical-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Mythological Rap",
    "slug": "mythological-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Nu Metal",
    "slug": "nu-metal",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Oriental Rap",
    "slug": "oriental-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Party Rap",
    "slug": "party-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Political Punk",
    "slug": "political-punk",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Political Rap",
    "slug": "political-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Pop",
    "slug": "pop",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Pop-rap",
    "slug": "pop-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Pop-rock",
    "slug": "pop-rock",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Pornorap",
    "slug": "pornorap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Power Metal",
    "slug": "power-metal",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Psychedelic Rap",
    "slug": "psychedelic-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Punk",
    "slug": "punk",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Punk Rap",
    "slug": "punk-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "R&B (Contemporary R&B)",
    "slug": "rnb",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Rage",
    "slug": "rage",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Rap",
    "slug": "rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Rap Metal",
    "slug": "rap-metal",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Reggaeton",
    "slug": "reggaeton",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Road Rap",
    "slug": "road-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Rock-Rap",
    "slug": "rock-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Sad Rap",
    "slug": "sad-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Shock Rap",
    "slug": "shock-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Slovak Rap",
    "slug": "slovak-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Soul",
    "slug": "soul",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Southern Rap",
    "slug": "southern-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Spoken Word",
    "slug": "spoken-word",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Street Rap",
    "slug": "street-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Theater Rap",
    "slug": "theater-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Traditional Metal",
    "slug": "traditional-metal",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Trap",
    "slug": "trap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Trap Metal",
    "slug": "trap-metal",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Turntablism",
    "slug": "turntablism",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "UK Garage",
    "slug": "uk-garage",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "UK Rap",
    "slug": "uk-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Underground Hip Hop",
    "slug": "underground-hip-hop",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Underground Rap",
    "slug": "underground-rap",
    "type": "zanr",
    "caseSensitive": false
  },
  {
    "name": "Underground Rock",
    "slug": "underground-rock",
    "type": "zanr",
    "caseSensitive": false
  }
]

export function getRegistryStats() {
  const byType = ENTITY_REGISTRY.reduce<Record<string, number>>((acc, e) => {
    acc[e.type] = (acc[e.type] || 0) + 1
    return acc
  }, {})
  return {
    total: ENTITY_REGISTRY.length,
    byType,
    totalAliases: ENTITY_REGISTRY.reduce((sum, e) => sum + (e.aliases?.length || 0), 0),
  }
}
